maintainer       "Yazino Technologies"
maintainer_email "dev@yazino.com"
license          "Apache 2.0"
description      "Installs/Configures LDAP"
long_description ""
version          "0.1"
name			 "ldap"
