#!/bin/bash

HATOP="/usr/local/bin/hatop"
SOCKET="/var/run/haproxy.sock"

if [ "$UID" != "0" ]; then
    echo "hatop must be run as root"
    exit 1
fi

if [ ! -x "$HATOP" ]; then
    echo "Cannot find $HATOP"
    exit 1
fi

$HATOP -s $SOCKET
