package com.yazino.platform.table;

public enum TableOperationResult {
	SUCCESS,
	UNKNOWN_TEMPLATE,
	UNKNOWN_CLIENT,
	FAILURE,
	UNKNOWN,
	GAME_TYPE_UNAVAILABLE,
	TABLE_ALREADY_EXISTS_FOR_GAMETYPE,
	TABLE_NOT_OWNED_BY_PLAYER,
    INVALID_CLIENT_FOR_GAMETYPE
}
