maintainer        "Yazino Technologies"
maintainer_email  "chef@yazino.com"
license           "Apache 2.0"
description       "Installs and configures RabbitMQ server"
version           "0.1"
name			 "rabbitmq"
