-- WEB-4252 - character set cleanup: reset the default character sets

ALTER DATABASE strataprod CHARACTER SET utf8#

-- This is to get around MySQL varying the case of constraints across OSs
DROP PROCEDURE IF EXISTS drop_game_configuration_gameid_constraints#
CREATE PROCEDURE drop_game_configuration_gameid_constraints()
  BEGIN
    DECLARE curr_table_name VARCHAR(100);
    DECLARE curr_constraint_name VARCHAR(100);
    DECLARE done BOOLEAN DEFAULT false;

    DECLARE fk_cursor CURSOR FOR SELECT table_name,constraint_name FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'strataprod' AND TABLE_NAME = 'GAME_CONFIGURATION_PROPERTY' AND COLUMN_NAME='GAME_ID' AND REFERENCED_TABLE_NAME IS NOT NULL;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = true;

    OPEN fk_cursor;
      cursor_loop: LOOP
      FETCH fk_cursor INTO curr_table_name,curr_constraint_name;
    IF done THEN
      LEAVE cursor_loop;
    END IF;

    SET @query = CONCAT('alter table ',curr_table_name,' drop foreign key ',curr_constraint_name);

    PREPARE stmt FROM @query;
      EXECUTE stmt;
      DEALLOCATE PREPARE stmt;
    END LOOP;

    CLOSE fk_cursor;
  END#

CALL drop_game_configuration_gameid_constraints()#
DROP PROCEDURE IF EXISTS drop_game_configuration_gameid_constraints#

ALTER TABLE GAME_CONFIGURATION
  DEFAULT CHARACTER SET utf8,
  MODIFY GAME_ID VARCHAR(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  MODIFY SHORT_NAME VARCHAR(50) CHARACTER SET utf8 NOT NULL,
  MODIFY DISPLAY_NAME VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL,
  MODIFY ALIASES VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL#

ALTER TABLE GAME_CONFIGURATION_PROPERTY
  DEFAULT CHARACTER SET utf8,
  MODIFY GAME_ID VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  MODIFY PROPERTY_NAME VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL,
  MODIFY PROPERTY_VALUE VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL#

ALTER TABLE GAME_CONFIGURATION_PROPERTY ADD CONSTRAINT FK_GAME_CONFIG_PROP_GAME_CONFIG_GAME_ID FOREIGN KEY (GAME_ID) REFERENCES GAME_CONFIGURATION (GAME_ID)#

ALTER TABLE IOS_PLAYER_DEVICE
  DEFAULT CHARACTER SET utf8,
  MODIFY GAME_TYPE VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  MODIFY DEVICE_TOKEN VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  MODIFY BUNDLE VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL#

ALTER TABLE PAYMENT_STATE
  DEFAULT CHARACTER SET utf8,
  MODIFY CASHIER_NAME VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  MODIFY EXTERNAL_TRANSACTION_ID VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  MODIFY STATE VARCHAR(20) CHARACTER SET utf8 NOT NULL#

ALTER TABLE PAYMENT_STATE_ANDROID
  DEFAULT CHARACTER SET utf8,
  MODIFY STATE VARCHAR(10) CHARACTER SET utf8 NOT NULL,
  MODIFY INTERNAL_TRANSACTION_ID VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  MODIFY GOOGLE_ORDER_NUMBER VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  MODIFY GAME_TYPE VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  MODIFY PRODUCT_ID VARCHAR(255) CHARACTER SET utf8 NOT NULL#

ALTER TABLE PLAYER_PROMOTION_STATUS DEFAULT CHARACTER SET utf8#

ALTER TABLE PROMOTION_CONFIG
  DEFAULT CHARACTER SET utf8,
  MODIFY CONFIG_KEY VARCHAR(50) CHARACTER SET utf8 NOT NULL,
  MODIFY CONFIG_VALUE VARCHAR(2000) CHARACTER SET utf8 NOT NULL#

ALTER TABLE PROMOTION_PLAYER_REWARD
  DEFAULT CHARACTER SET utf8,
  MODIFY DETAILS VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL#

ALTER TABLE RECURRING_TOURNAMENT_DEFINITION
  DEFAULT CHARACTER SET utf8,
  MODIFY TOURNAMENT_NAME VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  MODIFY TOURNAMENT_DESCRIPTION VARCHAR(512) CHARACTER SET utf8 NOT NULL,
  MODIFY PARTNER_ID VARCHAR(255) CHARACTER SET utf8 NOT NULL,
  MODIFY EXCLUSION_PERIODS TEXT CHARACTER SET utf8#

ALTER TABLE ZONG_TRANSACTION
  DEFAULT CHARACTER SET utf8,
  MODIFY FAILURE VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
  MODIFY GAMETYPE VARCHAR(20) CHARACTER SET utf8 NOT NULL,
  MODIFY ITEMREF VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
  MODIFY CONSUMERCURRENCY VARCHAR(4) CHARACTER SET utf8 DEFAULT NULL,
  MODIFY OUTPAYMENTCURRENCY VARCHAR(4) CHARACTER SET utf8 DEFAULT NULL#
