-- WEB-3953 - fix PLAYER_ID type

-- This is to get around MySQL varying the case of constraints across OSs
DROP PROCEDURE IF EXISTS drop_foreign_player_constraints#
CREATE PROCEDURE drop_foreign_player_constraints()
  BEGIN
    DECLARE curr_table_name VARCHAR(100);
    DECLARE curr_constraint_name VARCHAR(100);
    DECLARE done BOOLEAN DEFAULT false;

    DECLARE fk_cursor CURSOR FOR SELECT table_name,constraint_name FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'strataprod' AND TABLE_NAME IN ('AUTHENTICATION','LEADERBOARD_PLAYER','LEADERBOARD_RESULT', 'PLAYER_TROPHY') AND COLUMN_NAME='PLAYER_ID' AND REFERENCED_TABLE_NAME IS NOT NULL;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = true;

    OPEN fk_cursor;
      cursor_loop: LOOP
      FETCH fk_cursor INTO curr_table_name,curr_constraint_name;
    IF done THEN
      LEAVE cursor_loop;
    END IF;

    SET @query = CONCAT('alter table ',curr_table_name,' drop foreign key ',curr_constraint_name);

    PREPARE stmt FROM @query;
      EXECUTE stmt;
      DEALLOCATE PREPARE stmt;
    END LOOP;

    CLOSE fk_cursor;
  END#

CALL drop_foreign_player_constraints()#
DROP PROCEDURE IF EXISTS drop_foreign_player_constraints#

ALTER TABLE TOURNAMENT_PLAYER
  DROP FOREIGN KEY FK_TOURNAMENT_PLAYER_PLAYER_ID#

ALTER TABLE YAZINO_LOGIN
  DROP FOREIGN KEY FK_YAZINO_LOGIN_PLAYER_LOBBY_USER#

ALTER TABLE PLAYER_INBOX
  DROP FOREIGN KEY PLAYER_INBOX_PLAYER_ID_FK#

ALTER TABLE PLAYER
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#
  
ALTER TABLE PLAYER_INBOX
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_PLAYER_INBOX_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID)#

ALTER TABLE PLAYER_PROMOTION_STATUS
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE PLAYER_TROPHY
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_PLAYER_TROPHY_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID)#

ALTER TABLE PLAYER_RELATIONSHIP
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL,
  MODIFY RELATED_PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE PROMOTION_PLAYER
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE PROMOTION_PLAYER_REWARD
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE TABLE_INVITE
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE TABLE_INFO
  MODIFY OWNER_ID DECIMAL(16,2) DEFAULT NULL#

ALTER TABLE LOBBY_USER
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE YAZINO_LOGIN
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_YAZINO_LOGIN_PLAYER_LOBBY_USER FOREIGN KEY (PLAYER_ID) REFERENCES LOBBY_USER (PLAYER_ID)#

ALTER TABLE PAYMENT_STATE_ANDROID
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE LEADERBOARD_RESULT
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_LEADERBOARD_RESULT_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID)#

ALTER TABLE LEADERBOARD_PLAYER
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_LEADERBOARD_PLAYER_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID)#

ALTER TABLE INVITATIONS
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE IOS_PLAYER_DEVICE
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE AUTHENTICATION
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_AUTHENTICATION_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID)#

ALTER TABLE TOURNAMENT_PLAYER
  MODIFY PLAYER_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_TOURNAMENT_PLAYER_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID)#
