-- WEB-3953 - fix TOURNAMENT_ID type

ALTER TABLE TOURNAMENT_TABLE
  DROP FOREIGN KEY FK_TOURNAMENT_TABLE_TOURNAMENT_ID#

ALTER TABLE TOURNAMENT_PLAYER
  DROP FOREIGN KEY FK_TOURNAMENT_PLAYER_TOURNAMENT_ID#

ALTER TABLE TOURNAMENT_SUMMARY
  DROP FOREIGN KEY FK_TOURNAMENT_SUM_TOURNAMENT#

ALTER TABLE TOURNAMENT
  MODIFY TOURNAMENT_ID DECIMAL(16,2) NOT NULL#

ALTER TABLE TOURNAMENT_PLAYER
  MODIFY TOURNAMENT_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_TOURNAMENT_PLAYER_TOURNAMENT FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT (TOURNAMENT_ID)#

ALTER TABLE TOURNAMENT_SUMMARY
  MODIFY TOURNAMENT_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_TOURNAMENT_SUM_TOURNAMENT FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT (TOURNAMENT_ID)#

ALTER TABLE TOURNAMENT_TABLE
  MODIFY TOURNAMENT_ID DECIMAL(16,2) NOT NULL,
  ADD CONSTRAINT FK_TOURNAMENT_TABLE_TOURNAMENT FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT (TOURNAMENT_ID)#
