-- WEB-4260 - transform blocked into status

ALTER TABLE LOBBY_USER ADD COLUMN STATUS VARCHAR(1) NOT NULL DEFAULT 'A'#

UPDATE LOBBY_USER SET STATUS='B' WHERE BLOCKED=1#

CREATE TABLE PLAYER_PROFILE_STATUS_AUDIT (
    PLAYER_ID DECIMAL(16,2) NOT NULL,
    OLD_STATUS VARCHAR(1) NOT NULL,
    NEW_STATUS VARCHAR(1) NOT NULL,
    CHANGED_BY VARCHAR(64) NOT NULL,
    REASON VARCHAR(512) NOT NULL,
    CHANGED_TS TIMESTAMP NOT NULL DEFAULT NOW(),

    INDEX IDX_PP_STATUS_PLAYER_ID (PLAYER_ID)
  )#
