-- WEB-4279 - cache validation results in DB

CREATE TABLE EMAIL_VALIDATION (
  EMAIL_ADDRESS VARCHAR(255) NOT NULL PRIMARY KEY,
  STATUS VARCHAR(1) NOT NULL,
  IS_ROLE BIT NOT NULL DEFAULT 0,
  IS_DISPOSABLE BIT NOT NULL DEFAULT 0
) charset=utf8#
