-- WEB-4276 - track forex rates for packages

CREATE TABLE PAYMENT_FX (
  CURRENCY VARCHAR(3) NOT NULL,
  BASE_CURRENCY VARCHAR(3) NOT NULL DEFAULT 'USD',
  SETTLEMENT_DATE DATE NOT NULL,
  EXCHANGE_RATE DECIMAL(13,7) NOT NULL,

  PRIMARY KEY (CURRENCY, BASE_CURRENCY, SETTLEMENT_DATE)
) charset=utf8##

INSERT INTO PAYMENT_FX (CURRENCY,BASE_CURRENCY,SETTLEMENT_DATE,EXCHANGE_RATE) VALUES
  ('CAD','USD','2013-01-01','1.0000000'),
  ('AUD','USD','2013-01-01','1.0000000')#

ALTER TABLE PAYMENT_OPTION
  ADD COLUMN FX_PAYMENT_OPTION_ID VARCHAR(255)#

UPDATE PAYMENT_OPTION SET FX_PAYMENT_OPTION_ID = 'optionUSD1' WHERE LEVEL=1 AND CURRENCY IN ('CAD','AUD')#
UPDATE PAYMENT_OPTION SET FX_PAYMENT_OPTION_ID = 'optionUSD2' WHERE LEVEL=2 AND CURRENCY IN ('CAD','AUD')#
UPDATE PAYMENT_OPTION SET FX_PAYMENT_OPTION_ID = 'optionUSD3' WHERE LEVEL=3 AND CURRENCY IN ('CAD','AUD')#
UPDATE PAYMENT_OPTION SET FX_PAYMENT_OPTION_ID = 'optionUSD4' WHERE LEVEL=4 AND CURRENCY IN ('CAD','AUD')#
UPDATE PAYMENT_OPTION SET FX_PAYMENT_OPTION_ID = 'optionUSD5' WHERE LEVEL=5 AND CURRENCY IN ('CAD','AUD')#
UPDATE PAYMENT_OPTION SET FX_PAYMENT_OPTION_ID = 'optionUSD6' WHERE LEVEL=6 AND CURRENCY IN ('CAD','AUD')#

-- This is a dirty hack to get around MySQL's lack of subselect support in views. We should put a lower
-- bound on the concat as the dataset grows to avoid silliness.
CREATE OR REPLACE VIEW PAYMENT_FX_CURRENT AS
  SELECT currency,
         base_currency,
         substring_index(group_concat(exchange_rate order by settlement_date desc), ',', 1) exchange_rate
  FROM PAYMENT_FX
  WHERE settlement_date < now() + INTERVAL 2 DAY
  GROUP BY 1, 2#

CREATE OR REPLACE VIEW PAYMENT_OPTION_CURRENT AS
  SELECT  po.PAYMENT_OPTION_ID,
          po.LEVEL,
          po.CURRENCY,
          COALESCE(pfx.EXCHANGE_RATE * pox.PRICE, po.PRICE) as PRICE,
          po.CHIPS,
          po.CURRENCY_LABEL,
          COALESCE(pfx.EXCHANGE_RATE * poux.PRICE, pou.PRICE) as UPSELL_PRICE,
          pou.CHIPS as UPSELL_CHIPS,
          pop.PLATFORM,
          pou.PAYMENT_OPTION_ID as UPSELL_PAYMENT_OPTION_ID,
          pox.PAYMENT_OPTION_ID as FX_ID,
          pfx.EXCHANGE_RATE,
          pol.HEADER,
          pol.DESCRIPTION,
          pol.UPSELL_HEADER,
          pol.UPSELL_DESCRIPTION
  FROM PAYMENT_OPTION po
    LEFT JOIN PAYMENT_OPTION_LEVEL pol ON po.LEVEL = pol.LEVEL
    LEFT JOIN PAYMENT_OPTION pou ON pol.UPSELL_LEVEL = pou.LEVEL AND po.CURRENCY = pou.CURRENCY
    LEFT JOIN PAYMENT_OPTION_PLATFORM pop ON po.PAYMENT_OPTION_ID = pop.PAYMENT_OPTION_ID
    LEFT JOIN PAYMENT_OPTION_PLATFORM popu ON pou.PAYMENT_OPTION_ID = popu.PAYMENT_OPTION_ID
    LEFT JOIN PAYMENT_OPTION pox ON po.FX_PAYMENT_OPTION_ID = pox.PAYMENT_OPTION_ID
    LEFT JOIN PAYMENT_OPTION poux ON pou.FX_PAYMENT_OPTION_ID = poux.PAYMENT_OPTION_ID
    LEFT JOIN PAYMENT_FX_CURRENT pfx ON po.CURRENCY = pfx.CURRENCY AND pfx.BASE_CURRENCY = pox.CURRENCY
  WHERE popu.PLATFORM=pop.PLATFORM
  ORDER BY pop.PLATFORM,po.CURRENCY,po.LEVEL#
