-- WEB-4276 - add base currency to payment_option_current

CREATE OR REPLACE VIEW PAYMENT_OPTION_CURRENT AS
  SELECT  po.PAYMENT_OPTION_ID,
    po.LEVEL,
    po.CURRENCY,
    COALESCE(pfx.EXCHANGE_RATE * pox.PRICE * cur.COMMISSION_MULTIPLIER, po.PRICE) as PRICE,
    po.CHIPS,
    cur.CURRENCY_LABEL,
    COALESCE(pfx.EXCHANGE_RATE * poux.PRICE * cur.COMMISSION_MULTIPLIER, pou.PRICE) as UPSELL_PRICE,
    pou.CHIPS as UPSELL_CHIPS,
    pop.PLATFORM,
    pou.PAYMENT_OPTION_ID as UPSELL_PAYMENT_OPTION_ID,
    pox.PAYMENT_OPTION_ID as FX_ID,
    pfx.BASE_CURRENCY,
    pox.PRICE as BASE_CURRENCY_PRICE,
    pfx.EXCHANGE_RATE,
    pol.HEADER,
    pol.DESCRIPTION,
    pol.UPSELL_HEADER,
    pol.UPSELL_DESCRIPTION
  FROM PAYMENT_OPTION po
    LEFT JOIN PAYMENT_OPTION_LEVEL pol ON po.LEVEL = pol.LEVEL
    LEFT JOIN PAYMENT_OPTION pou ON pol.UPSELL_LEVEL = pou.LEVEL AND po.CURRENCY = pou.CURRENCY
    LEFT JOIN PAYMENT_OPTION_PLATFORM pop ON po.PAYMENT_OPTION_ID = pop.PAYMENT_OPTION_ID
    LEFT JOIN PAYMENT_OPTION_PLATFORM popu ON pou.PAYMENT_OPTION_ID = popu.PAYMENT_OPTION_ID
    LEFT JOIN PAYMENT_OPTION pox ON po.FX_PAYMENT_OPTION_ID = pox.PAYMENT_OPTION_ID
    LEFT JOIN PAYMENT_OPTION poux ON pou.FX_PAYMENT_OPTION_ID = poux.PAYMENT_OPTION_ID
    LEFT JOIN PAYMENT_FX_CURRENT pfx ON po.CURRENCY = pfx.CURRENCY AND pfx.BASE_CURRENCY = pox.CURRENCY
    LEFT JOIN CURRENCY cur ON po.CURRENCY = cur.CURRENCY_CODE
  WHERE popu.PLATFORM=pop.PLATFORM
  ORDER BY pop.PLATFORM,po.CURRENCY,po.LEVEL#
