-- WEB-4276 - add platform/payment option mappings for FACEBOOK_CANVAS

INSERT IGNORE INTO PAYMENT_OPTION_PLATFORM (PLATFORM, PAYMENT_OPTION_ID) VALUES
  ('FACEBOOK_CANVAS', 'optionUSD1'),
  ('FACEBOOK_CANVAS', 'optionUSD2'),
  ('FACEBOOK_CANVAS', 'optionUSD3'),
  ('FACEBOOK_CANVAS', 'optionUSD4'),
  ('FACEBOOK_CANVAS', 'optionUSD5'),
  ('FACEBOOK_CANVAS', 'optionUSD6'),
  ('FACEBOOK_CANVAS', 'optionCAD1'),
  ('FACEBOOK_CANVAS', 'optionCAD2'),
  ('FACEBOOK_CANVAS', 'optionCAD3'),
  ('FACEBOOK_CANVAS', 'optionCAD4'),
  ('FACEBOOK_CANVAS', 'optionCAD5'),
  ('FACEBOOK_CANVAS', 'optionCAD6'),
  ('FACEBOOK_CANVAS', 'optionAUD1'),
  ('FACEBOOK_CANVAS', 'optionAUD2'),
  ('FACEBOOK_CANVAS', 'optionAUD3'),
  ('FACEBOOK_CANVAS', 'optionAUD4'),
  ('FACEBOOK_CANVAS', 'optionAUD5'),
  ('FACEBOOK_CANVAS', 'optionAUD6'),
  ('FACEBOOK_CANVAS', 'optionGBP1'),
  ('FACEBOOK_CANVAS', 'optionGBP2'),
  ('FACEBOOK_CANVAS', 'optionGBP3'),
  ('FACEBOOK_CANVAS', 'optionGBP4'),
  ('FACEBOOK_CANVAS', 'optionGBP5'),
  ('FACEBOOK_CANVAS', 'optionGBP6'),
  ('FACEBOOK_CANVAS', 'optionEUR1'),
  ('FACEBOOK_CANVAS', 'optionEUR2'),
  ('FACEBOOK_CANVAS', 'optionEUR3'),
  ('FACEBOOK_CANVAS', 'optionEUR4'),
  ('FACEBOOK_CANVAS', 'optionEUR5'),
  ('FACEBOOK_CANVAS', 'optionEUR6')#
