-- WEB-4362 - added PAYMENT_CHARGEBACK

CREATE TABLE PAYMENT_CHARGEBACK (
  CHARGEBACK_REFERENCE VARCHAR(10) NOT NULL PRIMARY KEY,
  PROCESSING_DATE DATE NOT NULL,
  INTERNAL_TRANSACTION_ID VARCHAR(255) NOT NULL,
  TRANSACTION_DATE DATE NOT NULL,
  PLAYER_ID DECIMAL(16,2) NOT NULL,
  CHARGEBACK_REASON_CODE VARCHAR(4),
  CHARGEBACK_REASON VARCHAR(40) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(16) NOT NULL,
  AMOUNT DECIMAL(64,4) NOT NULL,
  CURRENCY_CODE VARCHAR(3) NOT NULL
) charset=utf8#
