DROP TABLE IF EXISTS GIFTS#

CREATE TABLE IF NOT EXISTS GIFTS (
  GIFT_ID int(11) NOT NULL AUTO_INCREMENT,
  SENDER_ID decimal(16,2) NOT NULL,
  RECEIVER_ID decimal(16,2) NOT NULL,
  CREATED_TS datetime NOT NULL,
  EXPIRY_TS datetime NOT NULL,
  ACKNOWLEDGED boolean NOT NULL,

  PRIMARY KEY (GIFT_ID),
  FOREIGN KEY FK_SEND_ID (SENDER_ID) REFERENCES LOBBY_USER(PLAYER_ID),
  FOREIGN KEY FK_REC_ID (RECEIVER_ID) REFERENCES LOBBY_USER(PLAYER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8#
