INSERT INTO `CLIENT` (`CLIENT_ID`, `CLIENT_FILE`, `GAME_TYPE`, `NUMBER_OF_SEATS`) VALUES ('Seven Player Slots', 'default.swf', 'SLOTS', 7)#
INSERT INTO `CLIENT_PROPERTY` (`CLIENT_ID`, `PROPERTY_NAME`, `PROPERTY_VALUE`) VALUES
  ('Seven Player Slots', 'MILLIS_REEL_SPINNED', '3000'),
  ('Seven Player Slots', 'MILLIS_REEL_SPINNED_BONUS', '1700')#

