-- ALTER TABLE PLAYER ADD COLUMN ts_last_played#

-- CREATE TABLE `PLAYER_NEW` (
--   `PLAYER_ID` decimal(16,2) NOT NULL,
--   `ACCOUNT_ID` decimal(16,2) NOT NULL,
--   `NAME` varchar(255) DEFAULT NULL,
--   `RELATIONSHIPS` mediumtext,
--   `PICTURE_LOCATION` varchar(610) DEFAULT NULL,
--   `PREFERRED_CURRENCY` varchar(3) DEFAULT NULL,
--   `ACHIEVEMENTS` text,
--   `REWARDS` varchar(255) DEFAULT NULL,
--   `ACHIEVEMENT_PROGRESS` text,
--   `LEVEL` text,
--   `TSCREATED` timestamp NULL DEFAULT NULL,
--   `IS_INSIDER` int(1) DEFAULT NULL,
--   `LAST_TOPUP_DATE` datetime DEFAULT NULL,
--   `PREFERRED_PAYMENT_METHOD` varchar(20) DEFAULT NULL,
--   `ts_last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   `ts_last_played` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`PLAYER_ID`),
--   KEY `PLAYER_ibfk_2` (`ACCOUNT_ID`),
--   KEY `IDX_PLAYER_NAME` (`NAME`),
--   KEY `IDX_PLAYER_TSCREATED` (`TSCREATED`),
--   KEY `idx_ts_last_update` (`ts_last_update`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8#

CREATE TABLE PLAYER_NEW SELECT * FROM PLAYER LIMIT 0#
ALTER TABLE PLAYER_NEW ADD COLUMN ts_last_played DATETIME NULL DEFAULT NULL#

INSERT INTO PLAYER_NEW SELECT *, null FROM PLAYER#
RENAME TABLE PLAYER TO PLAYER_OLD#
RENAME TABLE PLAYER_NEW TO PLAYER#

alter table AUTHENTICATION drop foreign key FK_AUTHENTICATION_PLAYER#
alter table LEADERBOARD_PLAYER drop foreign key FK_LEADERBOARD_PLAYER_PLAYER#
alter table LEADERBOARD_RESULT drop foreign key FK_LEADERBOARD_RESULT_PLAYER#
alter table PLAYER_INBOX drop foreign key FK_PLAYER_INBOX_PLAYER#
alter table PLAYER_TROPHY drop foreign key FK_PLAYER_TROPHY_PLAYER#
alter table TOURNAMENT_PLAYER drop foreign key FK_TOURNAMENT_PLAYER_PLAYER#

ALTER TABLE PLAYER ADD PRIMARY KEY (PLAYER_ID)#
ALTER TABLE PLAYER ADD INDEX IDX_PLAYER_NAME (NAME)#
ALTER TABLE PLAYER ADD INDEX IDX_PLAYER_CREATED (TSCREATED)#
ALTER TABLE PLAYER ADD INDEX IDX_TS_LAST_UPDATE (TS_LAST_UPDATE)#
ALTER TABLE PLAYER ADD INDEX IDX_TS_LAST_PLAYED (TS_LAST_PLAYED)#

alter table AUTHENTICATION add constraint FK_AUTHENTICATION_PLAYER foreign key (PLAYER_ID) references PLAYER (PLAYER_ID)#
alter table LEADERBOARD_PLAYER add constraint FK_LEADERBOARD_PLAYER_PLAYER foreign key (PLAYER_ID) references PLAYER (PLAYER_ID)#
alter table LEADERBOARD_RESULT add constraint FK_LEADERBOARD_RESULT_PLAYER foreign key (PLAYER_ID) references PLAYER (PLAYER_ID)#
alter table PLAYER_INBOX add constraint FK_PLAYER_INBOX_PLAYER foreign key (PLAYER_ID) references PLAYER (PLAYER_ID)#
alter table PLAYER_TROPHY add constraint FK_PLAYER_TROPHY_PLAYER foreign key (PLAYER_ID) references PLAYER (PLAYER_ID)#
alter table TOURNAMENT_PLAYER add constraint FK_TOURNAMENT_PLAYER_PLAYER foreign key (PLAYER_ID) references PLAYER (PLAYER_ID)#
