-- added PARTNER_ID to LOBBY_USER for Tango project

# DELIMITER #

SET OLD_ALTER_TABLE=1# -- this will force MySQL to use data_dir for the temp table rather than /tmp`

ALTER TABLE LOBBY_USER ADD COLUMN PARTNER_ID VARCHAR(255)#

UPDATE LOBBY_USER SET PARTNER_ID = 'PLAY_FOR_FUN' WHERE PARTNER_ID IS NULL#

ALTER TABLE LOBBY_USER CHANGE COLUMN PARTNER_ID PARTNER_ID VARCHAR(255) DEFAULT 'PLAY_FOR_FUN' NOT NULL#
ALTER TABLE LOBBY_USER ADD FOREIGN KEY FK_LOBBY_USER_PARTNER (PARTNER_ID) REFERENCES PARTNER (PARTNER_ID)#
