-- adds partner for TANGO

# DELIMITER #

UPDATE TABLE_INFO SET PARTNER_ID='PLAY_FOR_FUN' WHERE PARTNER_ID IN ('INTERNAL','FACEBOOK')#

delete from PARTNER WHERE PARTNER_ID='INTERNAL'#
delete from PARTNER WHERE PARTNER_ID='FACEBOOK'#
insert into PARTNER values ('TANGO',0,2500,0,2500,5000.00,2000,2000,1000)#
