-- WEB-4660 - remove obsolete columns from PARTNER

# DELIMITER #

ALTER TABLE PARTNER DROP COLUMN FAN_BALANCE#
ALTER TABLE PARTNER DROP COLUMN MAILINGLIST_BALANCE#
ALTER TABLE PARTNER DROP COLUMN BOOKMARK_BALANCE#
