-- WEB-4905 - add backing tables for disputed payments

CREATE TABLE PAYMENT_DISPUTE (
  INTERNAL_TRANSACTION_ID VARCHAR(255) NOT NULL PRIMARY KEY,
  CASHIER_NAME VARCHAR(255) NOT NULL,
  EXTERNAL_TRANSACTION_ID VARCHAR(255) NOT NULL,
  DISPUTE_STATUS VARCHAR(64) NOT NULL DEFAULT 'OPEN', -- OPEN, CLOSED
  DISPUTE_TS TIMESTAMP NOT NULL DEFAULT 0, -- needs zero to turn off silly bloody auto-update behaviour
  PLAYER_ID DECIMAL(16,2) NOT NULL,
  ACCOUNT_ID DECIMAL(16,2) NOT NULL,
  PRICE DECIMAL(64,4) NOT NULL,
  CURRENCY_CODE VARCHAR(3) NOT NULL,
  CHIPS DECIMAL(64,4) NOT NULL,
  TRANSACTION_TYPE VARCHAR(32) NOT NULL,
  GAME_TYPE VARCHAR(255),
  PLATFORM VARCHAR(32),
  PAYMENT_OPTION_ID VARCHAR(128),
  DESCRIPTION TEXT,
  RESOLUTION VARCHAR(64), -- REFUNDED_PLAYER_ERROR, REFUNDED_FRAUD, REFUNDED_OTHER, CHIPS_CREDITED, REFUSED, REFUSED_BANNED
  RESOLUTION_TS TIMESTAMP NULL,
  RESOLUTION_NOTE TEXT,
  RESOLVED_BY VARCHAR(64)
) charset=utf8#

