package strata.server.performance.rabbit;

/**
 * A message.
 */
public interface ReplayableMessage {
    /**
     * Returns the body of the message.
     *
     * @return the body, may be empty, never null
     */
    byte[] getBody();

    /**
     * Returns the routing key for this message.
     *
     * @return a string
     */
    String getRoutingKey();

    /**
     * Returns a message ID to be placed in the message properties.
     * @return null if an autogenerated ID should be used.
     */
    String getID();


    ReplayableMessage NULL = new ReplayableMessage() {
        @Override
        public byte[] getBody() {
            return new byte[0];
        }

        @Override
        public String getRoutingKey() {
            return toString();
        }

        @Override
        public String getID() {
            return null;
        }

        @Override
        public String toString() {
            return ReplayableMessage.class.getSimpleName().concat(".NULL");
        }

    };

}
