create or replace view `PLAYER`
AS select
   `U`.`PLAYER_ID` AS `PLAYER_ID`,
   `U`.`USER_ID` AS `USER_ID`,
   `P`.`ACCOUNT_ID` AS `ACCOUNT_ID`,
   `P`.`TSCREATED` AS `TSCREATED`,
   `P`.`IS_INSIDER` AS `IS_INSIDER`,
   `U`.`PICTURE_LOCATION` AS `PICTURE_LOCATION`
from (`PLAYER_DEFINITION` `P` inner join `LOBBY_USER` `U` on `P`.`PLAYER_ID` = `U`.PLAYER_ID)
#
