
DROP VIEW IF EXISTS PLAYER_PURCHASES#

-- CREATE VIEW PLAYER_PURCHASES AS
--  SELECT P.PLAYER_ID, P.USER_ID, ET.AUTO_ID, ET.MESSAGE_TIMESTAMP, (ET.CURRENCY_CODE='USD')*ET.AMOUNT AS USD, (ET.CURRENCY_CODE='EUR')*ET.AMOUNT AS EUR, (ET.CURRENCY_CODE='GBP')*ET.AMOUNT AS GBP
--  FROM strataproddw.EXTERNAL_TRANSACTION ET, strataprod.PLAYER P WHERE ET.ACCOUNT_ID=P.ACCOUNT_ID AND EXTERNAL_TRANSACTION_STATUS='SUCCESS'#