DROP FUNCTION IF EXISTS inferRevenueFromDefaultChips#

CREATE FUNCTION inferRevenueFromDefaultChips(DEFAULT_CHIPS INT)
RETURNS INT
	DETERMINISTIC
		BEGIN
			CASE DEFAULT_CHIPS
				WHEN 10000 THEN
					RETURN 5;
				WHEN 21000 THEN
					RETURN 10;
				WHEN 50000 THEN
					RETURN 15;
				WHEN 150000 THEN
					RETURN 20;
				WHEN 400000 THEN
					RETURN 50;
				WHEN 1000000 THEN
					RETURN 150;
				ELSE
					BEGIN
			    		SIGNAL SQLSTATE '45000'
			        		SET MESSAGE_TEXT = "Unrecognized payment option.";
			    	END;
			END CASE;
		END;
#

DROP FUNCTION IF EXISTS extractRevenueAttributableToPromotion#

CREATE FUNCTION extractRevenueAttributableToPromotion(DETAILS VARCHAR(255))
RETURNS INT
	DETERMINISTIC
		BEGIN
			DECLARE CHIPS_PART VARCHAR(255);
			DECLARE DEFAULT_CHIPS_PART VARCHAR(255);
			DECLARE ACTUAL_CHIPS_PART VARCHAR(255);
			DECLARE DEFAULT_CHIPS INT;
 			DECLARE ACTUAL_CHIPS INT;
			SET CHIPS_PART = SUBSTRING_INDEX(DETAILS, ',', -2);
			SET DEFAULT_CHIPS_PART := SUBSTRING_INDEX(CHIPS_PART, ',', 1);
			SET ACTUAL_CHIPS_PART := SUBSTRING_INDEX(CHIPS_PART, ',', -1);
			SET DEFAULT_CHIPS := CONVERT(TRIM(SUBSTRING_INDEX(DEFAULT_CHIPS_PART, '=', -1)), UNSIGNED);
 			SET ACTUAL_CHIPS := CONVERT(TRIM(SUBSTRING_INDEX(ACTUAL_CHIPS_PART, '=', -1)), UNSIGNED);

			RETURN IF(DEFAULT_CHIPS = ACTUAL_CHIPS, NULL, inferRevenueFromDefaultChips(DEFAULT_CHIPS));
		END;
#
