ALTER TABLE rpt_users_by_day_source_count CHANGE COLUMN SOURCE SOURCE VARCHAR(255) NOT NULL DEFAULT ''#
ALTER TABLE rpt_users_by_month_source_count CHANGE COLUMN SOURCE SOURCE VARCHAR(255) NOT NULL DEFAULT ''#
ALTER TABLE rpt_users_by_week_source_count CHANGE COLUMN SOURCE SOURCE VARCHAR(255) NOT NULL DEFAULT ''#