-- Move the old tables created by delta 10

DROP TABLE IF EXISTS TRANSACTION_LOG_OLD#
DROP TABLE IF EXISTS AUDIT_CLOSED_GAME_OLD#
DROP TABLE IF EXISTS AUDIT_CLOSED_GAME_PLAYER_OLD#
DROP TABLE IF EXISTS AUDIT_COMMAND_OLD#
DROP TABLE IF EXISTS ACCOUNT_SESSION_OLD#
