CREATE TABLE IF NOT EXISTS `APP_REQUEST` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TARGET_CLIENT` varchar(50) NOT NULL,
  `TITLE` varchar(256) NOT NULL DEFAULT '',
  `DESCRIPTION` varchar(256) NOT NULL DEFAULT '',
  `MESSAGE` varchar(100) NOT NULL DEFAULT '',
  `TRACKING` varchar(2048) DEFAULT NULL,
  `TARGET_COUNT` int(11) NOT NULL DEFAULT '0',
  `STATUS` tinyint(1) NOT NULL DEFAULT '0',
  `CREATED` datetime NOT NULL,
  `SENT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_CREATED` (`CREATED`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8#

CREATE TABLE IF NOT EXISTS `APP_REQUEST_TARGET` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `APP_REQUEST_ID` int(11) NOT NULL,
  `PLAYER_ID` bigint(20) NOT NULL,
  `EXTERNAL_ID` varchar(255) DEFAULT NULL,
  `GAME_TYPE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_TARGET` (`APP_REQUEST_ID`,`GAME_TYPE`,`PLAYER_ID`),
  KEY `IDX_NOTIFICATION_PLAYER` (`APP_REQUEST_ID`,`GAME_TYPE`,`PLAYER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=663471 DEFAULT CHARSET=utf8#

insert ignore into APP_REQUEST (ID, TARGET_CLIENT, TITLE, DESCRIPTION, MESSAGE, TARGET_COUNT, STATUS, CREATED, SENT)
  select ID, 'IOS', TITLE, DESCRIPTION, MESSAGE, TARGET_COUNT, STATUS, CREATED, SENT from IOS_PUSH_NOTIFICATION#

insert ignore into APP_REQUEST_TARGET (ID, APP_REQUEST_ID, PLAYER_ID, GAME_TYPE)
  select ID, NOTIFICATION_ID, PLAYER_ID, GAME_TYPE from IOS_PUSH_NOTIFICATION_TARGET#