DROP TABLE IF EXISTS `strataproddw`.`PROVIDER_REJECTED_EMAIL_ADDRESSES`#
CREATE TABLE PROVIDER_REJECTED_EMAIL_ADDRESSES
(
PLAYER_ID BIGINT(20) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
INFO varchar(255),
PRIMARY KEY (PLAYER_ID)
)#
