DROP TABLE IF EXISTS `PLAYER_REFERRER`
#

CREATE TABLE `PLAYER_REFERRER` AS (
  SELECT PLAYER_ID, REGISTRATION_REFERRER, REGISTRATION_PLATFORM
  FROM LOBBY_USER
)
#

ALTER TABLE `PLAYER_REFERRER` ADD PRIMARY KEY (PLAYER_ID)
#

ALTER TABLE `PLAYER_REFERRER` ADD COLUMN REGISTRATION_GAME_TYPE VARCHAR(32)
#

DROP TRIGGER IF EXISTS lobby_user_trigger
#

RENAME TABLE LOBBY_USER TO LOBBY_USER_INFO
#

ALTER TABLE LOBBY_USER_INFO DROP COLUMN REGISTRATION_REFERRER
#
ALTER TABLE LOBBY_USER_INFO DROP COLUMN REGISTRATION_PLATFORM 
#

CREATE VIEW LOBBY_USER
AS  
  SELECT LOBBY_USER_INFO.*, PLAYER_REFERRER.REGISTRATION_REFERRER, PLAYER_REFERRER.REGISTRATION_PLATFORM, PLAYER_REFERRER.REGISTRATION_GAME_TYPE
    FROM LOBBY_USER_INFO 
    LEFT JOIN PLAYER_REFERRER ON PLAYER_REFERRER.PLAYER_ID = LOBBY_USER_INFO.PLAYER_ID
#
