CREATE TABLE IF NOT EXISTS `GCM_PLAYER_DEVICE` (
    `PLAYER_ID` bigint(20) NOT NULL,
    `GAME_TYPE` varchar(255) NOT NULL,
    `REGISTRATION_ID` varchar(255) NOT NULL,
	PRIMARY KEY (`PLAYER_ID`, `GAME_TYPE`, `REGISTRATION_ID`),
	CONSTRAINT `UC_PLAYER_REGISTRATION_ID` UNIQUE (`PLAYER_ID`, `REGISTRATION_ID`)
)#
