DROP TABLE IF EXISTS NOTIFICATION_CAMPAIGN_CHANNEL#
DROP TABLE IF EXISTS NOTIFICATION_TARGET#
DROP TABLE IF EXISTS NOTIFICATION_CAMPAIGN CASCADE#

DROP TABLE IF EXISTS CAMPAIGN_DEFINITION#
DROP TABLE IF EXISTS CAMPAIGN_DEFINTION#
CREATE TABLE IF NOT EXISTS CAMPAIGN_DEFINITION (
    ID int(11) NOT NULL auto_increment,
    name varchar(256) DEFAULT '',
    segmentSqlQuery Blob,
    PRIMARY KEY (ID)
)#

DROP TABLE IF EXISTS CAMPAIGN_RUN#
CREATE TABLE IF NOT EXISTS CAMPAIGN_RUN (
  ID int(11) NOT NULL auto_increment,
  CAMPAIGN_ID int(11),
  RUN_TS timestamp default now(),
  PRIMARY KEY (ID),
  FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN_DEFINITION(ID)
)#

DROP TABLE IF EXISTS SEGMENT_SELECTION#
CREATE TABLE IF NOT EXISTS SEGMENT_SELECTION (
  CAMPAIGN_RUN_ID int(11) NOT NULL,
  PLAYER_ID BIGINT(11) NOT NULL,
  PRIMARY KEY (CAMPAIGN_RUN_ID, PLAYER_ID),
  FOREIGN KEY (CAMPAIGN_RUN_ID) REFERENCES CAMPAIGN_RUN(ID)
)#

-- CREATE TABLE IF NOT EXISTS CAMPAIGN_CHANNEL (
--   CAMPAIGN_ID int(11),
--   CHANNEL_ID int(11),
--   PRIMARY KEY (CAMPAIGN_ID, CHANNEL_ID),
--   FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN_DEFINITION(ID),
--   FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNEL_TYPE(ID)
-- )#

DROP TABLE IF EXISTS CAMPAIGN_CONTENT#
CREATE TABLE IF NOT EXISTS CAMPAIGN_CONTENT (
  CAMPAIGN_ID int(11),
  CONTENT_KEY varchar(255),
  CONTENT_VALUE blob,
  PRIMARY KEY (CAMPAIGN_ID, CONTENT_KEY),
  FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN_DEFINITION(ID)
)#

