DROP TABLE IF EXISTS CAMPAIGN_CONTENT#
CREATE TABLE IF NOT EXISTS CAMPAIGN_CONTENT (
  CAMPAIGN_ID int(11),
  CONTENT_KEY varchar(255),
  CONTENT_VALUE blob,
  PRIMARY KEY (CAMPAIGN_ID, CONTENT_KEY),
  FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN_DEFINITION(ID)
)#