DROP TABLE IF EXISTS CAMPAIGN_CHANEL#
CREATE TABLE CAMPAIGN_CHANNEL (
  CAMPAIGN_ID int(11),
  CHANNEL_ID int(11),
  PRIMARY KEY (CAMPAIGN_ID, CHANNEL_ID),
  FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN_DEFINITION(ID),
  FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNEL_TYPE(ID)
)#

INSERT INTO CAMPAIGN_CHANNEL (CAMPAIGN_ID, CHANNEL_ID) VALUES (1,1),(1,3),(1,4)#
INSERT INTO CAMPAIGN_CHANNEL (CAMPAIGN_ID, CHANNEL_ID) VALUES (2,1),(2,3),(2,4)#
INSERT INTO CAMPAIGN_CHANNEL (CAMPAIGN_ID, CHANNEL_ID) VALUES (3,1),(3,3),(3,4)#
INSERT INTO CAMPAIGN_CHANNEL (CAMPAIGN_ID, CHANNEL_ID) VALUES (4,1),(4,3),(4,4)#
INSERT INTO CAMPAIGN_CHANNEL (CAMPAIGN_ID, CHANNEL_ID) VALUES (5,1),(5,3),(5,4)#
INSERT INTO CAMPAIGN_CHANNEL (CAMPAIGN_ID, CHANNEL_ID) VALUES (6,1),(6,3),(6,4)#
INSERT INTO CAMPAIGN_CHANNEL (CAMPAIGN_ID, CHANNEL_ID) VALUES (7,1),(7,3),(7,4)#
