-- WEB-4173 - drop MAXIMILES_ID (aka USER_ID, aka PLAYER_PROFILE_ID)

DROP VIEW IF EXISTS YAZINO_LOGIN# 
CREATE  VIEW YAZINO_LOGIN
AS SELECT
   lu.PLAYER_ID AS PLAYER_ID,
   lu.EMAIL_ADDRESS AS EMAIL_ADDRESS
FROM LOBBY_USER lu#
