-- WEB-4244 - clean up of old auth tables for control-centre

DROP TABLE IF EXISTS OPERATIONS_PLATFORM#
DROP TABLE IF EXISTS OPERATIONS_ROLE#
DROP TABLE IF EXISTS OPERATIONS_USER#
DROP TABLE IF EXISTS ROLE_PEOPLE#
DROP TABLE IF EXISTS PARTNER_USERS#
DROP TABLE IF EXISTS USER#
DROP TABLE IF EXISTS ROLE#
