DROP TABLE IF EXISTS PROMOTION_CHIPS_PERCENTAGE#

CREATE TABLE PROMOTION_CHIPS_PERCENTAGE (
  ID                      INT(11) NOT NULL AUTO_INCREMENT,
  PROMOTION_DEFINITION_ID INT(11),
  PACKAGE_NUMBER          INT(11),
  PERCENTAGE              DECIMAL(5, 2),
  PRIMARY KEY (ID)
)#