CREATE TABLE CAMPAIGN_PROMOTION_CONFIG AS
select *
from PROMOTION_CONFIG
group by PROMOTION_DEFINITION_ID, CONFIG_KEY#

ALTER TABLE CAMPAIGN_PROMOTION_CONFIG ADD PRIMARY KEY(PROMOTION_DEFINITION_ID, CONFIG_KEY)#
