-- WEB-4274 - add forex, payment option details to external transactions

-- Allow null card numbers for payment methods without cards
ALTER TABLE EXTERNAL_TRANSACTION
  MODIFY COLUMN CREDIT_CARD_NUMBER VARCHAR(16),
  ADD COLUMN PAYMENT_OPTION_ID VARCHAR(128),
  ADD COLUMN BASE_CURRENCY_AMOUNT DECIMAL(64,4),
  ADD COLUMN BASE_CURRENCY_CODE VARCHAR(3),
  ADD COLUMN EXCHANGE_RATE DECIMAL(12,6)#
