ALTER TABLE PROMOTION_DEFINITION ADD PROMOTION_TYPE varchar(20)#
UPDATE PROMOTION_DEFINITION SET PROMOTION_TYPE = 'BUY_CHIPS'#
ALTER TABLE PROMOTION_DEFINITION MODIFY PROMOTION_TYPE varchar(20) NOT NULL#
