DROP TABLE IF EXISTS CAMPAIGN_CHANNEL_CONFIG#
CREATE TABLE IF NOT EXISTS CAMPAIGN_CHANNEL_CONFIG (
  CAMPAIGN_ID int(11),
  CONFIG_KEY varchar(50),
  CONFIG_VALUE varchar(20000),
  PRIMARY KEY (CAMPAIGN_ID, CONFIG_KEY),
  FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN_DEFINITION(ID),
  INDEX idx_campaign_id (CAMPAIGN_ID asc)
)#

