DROP TABLE IF EXISTS CAMPAIGN_TARGET#
CREATE TABLE IF NOT EXISTS CAMPAIGN_TARGET (
  CAMPAIGN_ID int(11),
  PLAYER_ID int(11),
  PRIMARY KEY (CAMPAIGN_ID, PLAYER_ID),
  FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN_DEFINITION(ID),
  INDEX idx_ct_campaign_id (CAMPAIGN_ID asc)
)#
