CREATE TABLE MESSAGING_PLAYER_DEVICE_REGISTRATION (
  PLAYER_ID bigint(20) NOT NULL,
  GAME_TYPE varchar(255) NOT NULL,
  PLATFORM varchar(255) NOT NULL,
  REGISTRATION_ID varchar(255) NOT NULL,
  LAST_UPDATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PLAYER_ID, GAME_TYPE, PLATFORM, REGISTRATION_ID)
)#