-- WEB-4579 - Clean up more report tables

DROP EVENT IF EXISTS evtFillRegistrationByDateSourceAndPlatform#
DROP EVENT IF EXISTS evtFillInvitesSummary#
DROP EVENT IF EXISTS extractLastPlayed#
DROP EVENT IF EXISTS rptExtractFacebookNewRegistrations#
DROP EVENT IF EXISTS rptExtractNewRegistrations#

DROP TRIGGER IF EXISTS players_by_platform_and_time_trigger#
DROP TRIGGER IF EXISTS users_by_day_trigger#
DROP TRIGGER IF EXISTS users_by_week_trigger#
DROP TRIGGER IF EXISTS users_by_month_trigger#
DROP TRIGGER IF EXISTS players_by_day_trigger#
DROP TRIGGER IF EXISTS players_by_week_trigger#
DROP TRIGGER IF EXISTS players_by_month_trigger#
DROP TRIGGER IF EXISTS account_user_activity_trigger_weekly#
DROP TRIGGER IF EXISTS account_user_activity_trigger_monthly#
DROP TRIGGER IF EXISTS account_user_activity_trigger#
DROP TRIGGER IF EXISTS account_activity_weekly_trigger#
DROP TRIGGER IF EXISTS account_activity_monthly_trigger#
DROP TRIGGER IF EXISTS account_activity_trigger#
DROP TRIGGER IF EXISTS player_definition_trigger#
DROP TRIGGER IF EXISTS invites_by_player_trigger#

DROP PROCEDURE IF EXISTS init_agg_transaction_log_by_date_gvt_acc#
DROP PROCEDURE IF EXISTS rptExtractDistinctPlayers#
DROP PROCEDURE IF EXISTS rptExtractDistinctUsersByGameSource#
DROP PROCEDURE IF EXISTS rptExtractDistinctUsersByGameSourceMonthly#
DROP PROCEDURE IF EXISTS rptExtractDistinctUsersByGameSourceWeekly#
DROP PROCEDURE IF EXISTS rptExtractFacebookNewRegistrations#
DROP PROCEDURE IF EXISTS rptExtractNewRegistrations#
DROP PROCEDURE IF EXISTS fillRegistrationByDateSourceAndPlatform#
DROP PROCEDURE IF EXISTS fillInvitesSummary#
DROP PROCEDURE IF EXISTS extractLastPlayed#
DROP PROCEDURE IF EXISTS rptExtractFacebookNewRegistrations#
DROP PROCEDURE IF EXISTS rptExtractNewRegistrations#

DROP VIEW IF EXISTS rpt_player_sources#
DROP VIEW IF EXISTS rpt_purchases_per_day#

DROP TABLE IF EXISTS rpt_account_activity#
DROP TABLE IF EXISTS rpt_account_activity_monthly#
DROP TABLE IF EXISTS rpt_account_activity_weekly#
DROP TABLE IF EXISTS rpt_account_sources_mv#
DROP TABLE IF EXISTS rpt_activity_by_account_id#
DROP TABLE IF EXISTS rpt_activity_by_account_id_monthly#
DROP TABLE IF EXISTS rpt_activity_by_account_id_weekly#
DROP TABLE IF EXISTS rpt_distinct_players#
DROP TABLE IF EXISTS rpt_distinct_players_monthly#
DROP TABLE IF EXISTS rpt_distinct_players_weekly#
DROP TABLE IF EXISTS rpt_distinct_users_by_game_source#
DROP TABLE IF EXISTS rpt_distinct_users_by_game_source_monthly#
DROP TABLE IF EXISTS rpt_distinct_users_by_game_source_weekly#
DROP TABLE IF EXISTS rpt_facebook_registration#
DROP TABLE IF EXISTS rpt_invitation#
DROP TABLE IF EXISTS rpt_invites_activity#
DROP TABLE IF EXISTS rpt_invites_by_player_and_day#
DROP TABLE IF EXISTS rpt_mm_export_status#
DROP TABLE IF EXISTS rpt_mv_stats_acquisition#
DROP TABLE IF EXISTS rpt_mv_stats_activity#
DROP TABLE IF EXISTS rpt_mv_stats_games#
DROP TABLE IF EXISTS rpt_mv_stats_purchases#
DROP TABLE IF EXISTS rpt_mv_stats_tournaments#
DROP TABLE IF EXISTS rpt_player_sources#
DROP TABLE IF EXISTS rpt_player_sources_mv#
DROP TABLE IF EXISTS rpt_player_sources_mv_tmp#
DROP TABLE IF EXISTS rpt_players_by_day#
DROP TABLE IF EXISTS rpt_players_by_month#
DROP TABLE IF EXISTS rpt_players_by_platform_and_day#
DROP TABLE IF EXISTS rpt_players_by_platform_and_hour#
DROP TABLE IF EXISTS rpt_players_by_platform_and_time#
DROP TABLE IF EXISTS rpt_players_by_platform_and_time_count#
DROP TABLE IF EXISTS rpt_players_by_platform_and_time_count_all_sources#
DROP TABLE IF EXISTS rpt_players_by_platform_and_week#
DROP TABLE IF EXISTS rpt_players_by_week#
DROP TABLE IF EXISTS rpt_players_daily#
DROP TABLE IF EXISTS rpt_players_monthly#
DROP TABLE IF EXISTS rpt_players_weekly#
DROP TABLE IF EXISTS rpt_purchases_per_day#
DROP TABLE IF EXISTS rpt_recent_registrations#
DROP TABLE IF EXISTS rpt_registration#
DROP TABLE IF EXISTS rpt_registrations_by_date_source_and_platform#
DROP TABLE IF EXISTS rpt_registrations_per_source_and_day#
DROP TABLE IF EXISTS rpt_registrations_per_source_and_month#
DROP TABLE IF EXISTS rpt_registrations_per_source_and_week#
DROP TABLE IF EXISTS rpt_report_status#
DROP TABLE IF EXISTS rpt_tmp_account_activity#
DROP TABLE IF EXISTS rpt_tmp_table_activity#
DROP TABLE IF EXISTS rpt_users_by_day#
DROP TABLE IF EXISTS rpt_users_by_day_source_count#
DROP TABLE IF EXISTS rpt_users_by_month#
DROP TABLE IF EXISTS rpt_users_by_month_source_count#
DROP TABLE IF EXISTS rpt_users_by_week#
DROP TABLE IF EXISTS rpt_users_by_week_source_count#
DROP TABLE IF EXISTS rpt_users_daily#
DROP TABLE IF EXISTS rpt_users_monthly#
DROP TABLE IF EXISTS rpt_users_weekly#
DROP TABLE IF EXISTS AGG_TRANSACTION_LOG_BY_DATE_GVT_ACC#
DROP TABLE IF EXISTS APP_REQUEST_TARGET_OLD#
