-- WEB-4579 - Clean up obsolete event tables

# DELIMITER #

DROP EVENT IF EXISTS evt_set_user_country_from_geoloc#
DROP EVENT IF EXISTS evt_fill_bi_verification_status#
DROP EVENT IF EXISTS evt_set_user_country_from_geoloc#

DROP PROCEDURE IF EXISTS bi_verification_status#
DROP PROCEDURE IF EXISTS fill_bi_verification_status#
DROP PROCEDURE IF EXISTS popAccountActivity#
DROP PROCEDURE IF EXISTS popLastPlayed#
DROP PROCEDURE IF EXISTS player_status_session_update#
DROP PROCEDURE IF EXISTS fillDailyMailStats#
DROP PROCEDURE IF EXISTS extractAccountActivityAt#
DROP PROCEDURE IF EXISTS extractSessionState#
DROP PROCEDURE IF EXISTS migrate_player_levels#
DROP PROCEDURE IF EXISTS count_accepted_invite#
DROP PROCEDURE IF EXISTS extractLocations#
DROP PROCEDURE IF EXISTS extractLocationInfo#
DROP PROCEDURE IF EXISTS extractLocationsFrom#
DROP PROCEDURE IF EXISTS createAndFillTmpLatestCommands#

DROP VIEW IF EXISTS AD_TRACKING#
DROP VIEW IF EXISTS game_type#
DROP VIEW IF EXISTS lobby_user#
DROP VIEW IF EXISTS player#
DROP VIEW IF EXISTS player_info#
DROP VIEW IF EXISTS players_yesterday#
DROP VIEW IF EXISTS rpt_player_sources_mv#
DROP VIEW IF EXISTS table_info#
DROP VIEW IF EXISTS unique_players_source_yesterday#
DROP VIEW IF EXISTS unique_players_tournament_yesterday#
DROP VIEW IF EXISTS unique_players_yesterday#
DROP VIEW IF EXISTS unique_users_yesterday#
DROP VIEW IF EXISTS yazino_login#

DROP TABLE IF EXISTS GEOLOC_ACCOUNTS#
DROP TABLE IF EXISTS GEOLOC_LOCATIONS#
DROP TABLE IF EXISTS GEOLOC_RANGES#
DROP TABLE IF EXISTS GEOLOC_SESSIONS#
DROP TABLE IF EXISTS PLAYER_STATUS_CURRENT#
DROP TABLE IF EXISTS bi_verification_status#
DROP TABLE IF EXISTS bi_verification_status_direct#
DROP TABLE IF EXISTS EXTERNAL_TRANSACTION_ITUNES#
DROP TABLE IF EXISTS PROGRESS_BAR#
DROP TABLE IF EXISTS registration_by_date_platform_game_type_source#
DROP TABLE IF EXISTS AD_TRACKING_OLD#
DROP TABLE IF EXISTS INVITATIONS#
DROP TABLE IF EXISTS LEADERBOARD_POSITION#
DROP TABLE IF EXISTS LEADERBOARD#
DROP TABLE IF EXISTS TOURNAMENT_PLAYER#
DROP TABLE IF EXISTS TOURNAMENT_PLAYER_SUMMARY#
DROP TABLE IF EXISTS TOURNAMENT_SUMMARY#
DROP TABLE IF EXISTS TOURNAMENT_VARIATION_TEMPLATE#
DROP TABLE IF EXISTS PLAYER_REFERRER#
DROP TABLE IF EXISTS TABLE_DEFINITION#
DROP TABLE IF EXISTS GAME_VARIATION_TEMPLATE#
DROP TABLE IF EXISTS LAST_PLAYED_UNIQUE#
DROP TABLE IF EXISTS LAST_PLAYED#
DROP TABLE IF EXISTS PLAYER_CLOSED_SESSION#
DROP TABLE IF EXISTS PLAYER_ACCOUNT_INFO#
DROP TABLE IF EXISTS PLAYER_LEVEL#
DROP TABLE IF EXISTS LOBBY_USER_INFO#
DROP TABLE IF EXISTS PLAYER_DEFINITION#
DROP TABLE IF EXISTS ACCOUNT#
DROP TABLE IF EXISTS TOURNAMENT#
