-- remove duplicate external transactions for itune payments

CREATE TABLE IF NOT EXISTS `EXTERNAL_TRANSACTION_ITUNES` (
  `AUTO_ID` bigint(20) NOT NULL,
  `ACCOUNT_ID` int(11) NOT NULL,
  `INTERNAL_TRANSACTION_ID` varchar(255) NOT NULL,
  `EXTERNAL_TRANSACTION_ID` varchar(255) DEFAULT NULL,
  `MESSAGE` text NOT NULL,
  `MESSAGE_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CURRENCY_CODE` varchar(3) NOT NULL,
  `AMOUNT` decimal(64,4) NOT NULL,
  `CREDIT_CARD_NUMBER` varchar(16) NOT NULL,
  `CASHIER_NAME` varchar(255) NOT NULL,
  `EXTERNAL_TRANSACTION_STATUS` varchar(255) DEFAULT NULL,
  `AMOUNT_CHIPS` decimal(64,4) NOT NULL DEFAULT '0.0000',
  `VERSION` int(11) NOT NULL DEFAULT '0',
  `TRANSACTION_TYPE` varchar(32) DEFAULT NULL,
  `GAME_TYPE` varchar(255) DEFAULT NULL,
  `FAILURE_REASON` varchar(255) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=latin1#


INSERT INTO EXTERNAL_TRANSACTION_ITUNES (
SELECT * FROM EXTERNAL_TRANSACTION WHERE AUTO_ID IN (
SELECT max(e.AUTO_ID) FROM EXTERNAL_TRANSACTION e WHERE e.TRANSACTION_TYPE = 'iTunes Deposit' GROUP BY e.EXTERNAL_TRANSACTION_ID HAVING count(e.EXTERNAL_TRANSACTION_ID) = 2))#

DELETE FROM EXTERNAL_TRANSACTION WHERE AUTO_ID IN (select AUTO_ID from EXTERNAL_TRANSACTION_ITUNES)#

