CREATE TABLE PROMOTION_ARCHIVE (
  PROMO_ID int(11) NOT NULL,
  NAME varchar(255) NOT NULL,
  START_DATE datetime NOT NULL,
  END_DATE datetime NOT NULL,
  REWARD_CHIPS int(11) NOT NULL,
  MAX_REWARDS int NOT NULL DEFAULT '1' comment 'maximum number of times chips can be awarded per player',
  PRIMARY KEY (PROMO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8#

CREATE TABLE PROMOTION_PLAYER_ARCHIVE (
  PROMO_ID int(11) NOT NULL,
  PLAYER_ID bigint(20) NOT NULL,
  NUMBER_OF_REWARDS int(11) DEFAULT NULL COMMENT 'number of times promotion redeemed, always <= PROMOTION.max_rewards',
  LAST_REWARDED_DATE datetime DEFAULT NULL,
  PRIMARY KEY (PROMO_ID,PLAYER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8#

CREATE VIEW PROMOTION AS
  SELECT PROMO_ID, NAME, START_DATE, END_DATE FROM strataprod.PROMOTION
  UNION
  SELECT PROMO_ID, NAME, START_DATE, END_DATE FROM PROMOTION_ARCHIVE#

CREATE VIEW PROMOTION_PLAYER AS
  SELECT PROMO_ID, PLAYER_ID FROM strataprod.PROMOTION_PLAYER
  UNION
  SELECT PROMO_ID, PLAYER_ID FROM PROMOTION_PLAYER_ARCHIVE#
