alter table PROMOTION_PLAYER_ARCHIVE modify column PLAYER_ID int(11) not null#

drop view if exists PROMOTION_PLAYER#
CREATE VIEW PROMOTION_PLAYER AS
  SELECT PROMO_ID, PLAYER_ID FROM strataprod.PROMOTION_PLAYER
  UNION
  SELECT PROMO_ID, PLAYER_ID FROM PROMOTION_PLAYER_ARCHIVE#