drop view if exists PROMOTION#
CREATE VIEW PROMOTION_VIEW AS
  SELECT PROMO_ID, NAME, START_DATE, END_DATE FROM strataprod.PROMOTION
  UNION
  SELECT PROMO_ID, NAME, START_DATE, END_DATE FROM PROMOTION_ARCHIVE#

drop view if exists PROMOTION_PLAYER#
CREATE VIEW PROMOTION_PLAYER_VIEW AS
  SELECT PROMO_ID, PLAYER_ID FROM strataprod.PROMOTION_PLAYER
  UNION
  SELECT PROMO_ID, PLAYER_ID FROM PROMOTION_PLAYER_ARCHIVE#