alter table PROMOTION_PLAYER_ARCHIVE modify column PLAYER_ID BIGINT(20) not null#

drop view if exists PROMOTION_PLAYER_VIEW#
CREATE VIEW PROMOTION_PLAYER_VIEW AS
  SELECT PROMO_ID, PLAYER_ID FROM strataprod.PROMOTION_PLAYER
  UNION
  SELECT PROMO_ID, PLAYER_ID FROM PROMOTION_PLAYER_ARCHIVE#