-- Moving tables from the main schema

-- The src/main/sh/migrate-bo-data.sh script can be used to migrate the not audit/txlog data
-- into these tables.

DROP TABLE IF EXISTS ACCOUNT_SESSION#
DROP TABLE IF EXISTS AUDIT_CLOSED_GAME#
DROP TABLE IF EXISTS AUDIT_CLOSED_GAME_PLAYER#
DROP TABLE IF EXISTS AUDIT_COMMAND#
DROP TABLE IF EXISTS EXTERNAL_TRANSACTION#
DROP TABLE IF EXISTS INVITATIONS#
DROP TABLE IF EXISTS PARTNER_USERS#
DROP TABLE IF EXISTS REQUESTMAP#
DROP TABLE IF EXISTS ROLE_PEOPLE#
DROP TABLE IF EXISTS ROLE#
DROP TABLE IF EXISTS TRANSACTION_LOG#
DROP TABLE IF EXISTS USER#

CREATE TABLE ACCOUNT_SESSION (
  SESSION_ID int(11) NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID int(11) NOT NULL,
  SESSION_KEY varchar(255) NOT NULL,
  TSSTARTED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION int(11) NOT NULL DEFAULT '0',
  IP_ADDRESS varchar(40) DEFAULT NULL,
  REFERER varchar(1000) DEFAULT NULL,

  PRIMARY KEY (SESSION_ID),
  KEY IDX_SESSION_ACCOUNT (ACCOUNT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#

CREATE TABLE AUDIT_CLOSED_GAME (
  auto_id int(11) NOT NULL AUTO_INCREMENT,
  AUDIT_LABEL varchar(255) NOT NULL,
  HOSTNAME varchar(255) NOT NULL,
  AUDIT_TS datetime NOT NULL,
  DBWRITE_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  TABLE_ID decimal(64,2) DEFAULT NULL,
  GAME_ID int(11) DEFAULT NULL,
  GAME_INCREMENT int(11) DEFAULT NULL,
  OBSERVABLE_STATUS longtext,
  INTERNAL_STATUS longtext,

  PRIMARY KEY (auto_id),
  KEY IDX_TABLE_ID (TABLE_ID),
  KEY IDX_GAME_ID (GAME_ID),
  KEY IDX_AUDIT_CLOSED_GAME_AUDIT_TS (AUDIT_TS),
  KEY IDX_AUDIT_CLOSED_GAME_HOSTNAME (HOSTNAME)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#

CREATE TABLE AUDIT_CLOSED_GAME_PLAYER (
  auto_id int(11) NOT NULL AUTO_INCREMENT,
  AUDIT_LABEL varchar(255) NOT NULL,
  HOSTNAME varchar(255) NOT NULL,
  AUDIT_TS datetime NOT NULL,
  DBWRITE_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  TABLE_ID decimal(64,2) NOT NULL,
  GAME_ID decimal(64,2) NOT NULL,
  PLAYER_ID bigint(20) NOT NULL,

  PRIMARY KEY (auto_id),
  KEY AUDIT_LABEL (AUDIT_LABEL),
  KEY IDX_ACGP_P (PLAYER_ID,GAME_ID),
  KEY IDX_ACGP_P1 (PLAYER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#

CREATE TABLE AUDIT_COMMAND (
  auto_id bigint(20) NOT NULL AUTO_INCREMENT,
  AUDIT_LABEL varchar(255) NOT NULL,
  HOSTNAME varchar(255) NOT NULL,
  AUDIT_TS datetime NOT NULL,
  DBWRITE_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  COMMAND_ID varchar(255) NOT NULL,
  TABLE_ID decimal(64,2) NOT NULL,
  GAME_ID bigint(20) DEFAULT NULL,
  ACCOUNT_ID decimal(64,2) NOT NULL,
  COMMAND_TYPE varchar(255) NOT NULL,
  COMMAND_ARGS text,

  PRIMARY KEY (auto_id),
  KEY AUDIT_LABEL (AUDIT_LABEL)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#

CREATE TABLE EXTERNAL_TRANSACTION (
  AUTO_ID bigint(20) NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID int(11) NOT NULL,
  INTERNAL_TRANSACTION_ID varchar(255) NOT NULL,
  EXTERNAL_TRANSACTION_ID varchar(255) DEFAULT NULL,
  MESSAGE text NOT NULL,
  MESSAGE_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CURRENCY_CODE varchar(3) NOT NULL,
  AMOUNT decimal(64,4) NOT NULL,
  CREDIT_CARD_NUMBER varchar(16) NOT NULL,
  CASHIER_NAME varchar(255) NOT NULL,
  EXTERNAL_TRANSACTION_STATUS varchar(255) DEFAULT NULL,
  AMOUNT_CHIPS decimal(64,4) NOT NULL DEFAULT '0.0000',
  VERSION int(11) NOT NULL DEFAULT '0',
  TRANSACTION_TYPE varchar(32) DEFAULT NULL,
  GAME_TYPE varchar(255) DEFAULT NULL,

  PRIMARY KEY (AUTO_ID),
  KEY IDX_EXTERNAL_TRANSACTION_ACCOUNT (ACCOUNT_ID),
  KEY FK_EXTERNAL_TRANSACTION_TRANSACTION_TYPE (TRANSACTION_TYPE),
  KEY IDX_EXTERNAL_TRANSACTION_INTERNAL_ID (INTERNAL_TRANSACTION_ID),
  KEY IDX_EXTERNAL_TRANSACTION_EXTERNAL_ID (EXTERNAL_TRANSACTION_ID),
  KEY IDX_ET_TIMESTAMP (MESSAGE_TIMESTAMP)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#

CREATE TABLE INVITATIONS (
  PLAYER_ID bigint(20) NOT NULL,
  RECIPIENT_IDENTIFIER varchar(255) NOT NULL,
  INVITED_FROM varchar(10) NOT NULL,
  STATUS varchar(20) NOT NULL,
  REWARD int(11) DEFAULT NULL,
  CREATED_TS timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  UPDATED_TS timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',

  PRIMARY KEY (PLAYER_ID,RECIPIENT_IDENTIFIER,INVITED_FROM),
  KEY IDX_INVITATIONS_USER_ID (PLAYER_ID),
  KEY IDX_INVITATIONS_INVITED (RECIPIENT_IDENTIFIER,INVITED_FROM)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#


CREATE TABLE USER (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  VERSION bigint(20) NOT NULL DEFAULT '0',
  DESCRIPTION varchar(255) NOT NULL,
  EMAIL varchar(255) NOT NULL,
  EMAIL_SHOW bit(1) NOT NULL,
  ENABLED bit(1) NOT NULL,
  PASSWD varchar(255) NOT NULL,
  USER_REAL_NAME varchar(255) NOT NULL,
  USERNAME varchar(255) NOT NULL,

  PRIMARY KEY (ID),
  UNIQUE KEY UC_USER_USERNAME (USERNAME)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1#

CREATE TABLE PARTNER_USERS (
  USER_ID bigint(20) NOT NULL,
  PARTNER_ID varchar(255) NOT NULL,

  PRIMARY KEY (USER_ID,PARTNER_ID),
  CONSTRAINT FK_PARTNER_USERS_USER FOREIGN KEY (USER_ID) REFERENCES USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#

CREATE TABLE REQUESTMAP (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  VERSION bigint(20) NOT NULL DEFAULT '0',
  CONFIG_ATTRIBUTE varchar(255) NOT NULL,
  URL varchar(255) NOT NULL,

  PRIMARY KEY (ID),
  UNIQUE KEY UC_REQUESTMAP_URL (URL)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=latin1#

CREATE TABLE ROLE (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  VERSION bigint(20) NOT NULL DEFAULT '0',
  AUTHORITY varchar(255) NOT NULL,
  DESCRIPTION varchar(255) NOT NULL,

  PRIMARY KEY (ID),
  UNIQUE KEY UC_ROLE_AUTHORITY (AUTHORITY)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1#

CREATE TABLE ROLE_PEOPLE (
  USER_ID bigint(20) NOT NULL,
  ROLE_ID bigint(20) NOT NULL,

  PRIMARY KEY (ROLE_ID,USER_ID),
  CONSTRAINT FK_ROLE_PEOPLE_USER FOREIGN KEY (USER_ID) REFERENCES USER (ID),
  CONSTRAINT FK_ROLE_PEOPLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#

CREATE TABLE TRANSACTION_LOG (
  TRANSACTION_LOG_ID bigint(20) NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID int(11) NOT NULL,
  AMOUNT decimal(64,4) NOT NULL,
  REFERENCE varchar(255) DEFAULT NULL,
  TSEXECUTED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION int(11) NOT NULL DEFAULT '0',
  TRANSACTION_TYPE varchar(32) NOT NULL,
  AUDIT_LABEL varchar(255) DEFAULT NULL,
  TRANSACTION_TS timestamp NULL DEFAULT NULL,
  RUNNING_BALANCE decimal(64,4) DEFAULT NULL,

  PRIMARY KEY (TRANSACTION_LOG_ID),
  KEY IDX_REFERENCE (REFERENCE),
  KEY IDX_ACCOUNT_ID (ACCOUNT_ID),
  KEY IDX_TRANSACTION_LOG_TRANSACTION_TYPE (TRANSACTION_TYPE),
  KEY IDX_TRANSACTION_LOG_REF_TX_TYPE (REFERENCE,TRANSACTION_TYPE),
  KEY IDX_AUDIT_LABEL (AUDIT_LABEL),
  KEY IDX_TRANSACTION_TS (TRANSACTION_TS)
) ENGINE=InnoDB DEFAULT CHARSET=latin1#
