DROP PROCEDURE IF EXISTS fix_operations#

CREATE PROCEDURE fix_operations() BEGIN
IF EXISTS(SELECT *  FROM information_schema.columns 
  WHERE TABLE_SCHEMA='strataproddw' AND table_name='OPERATIONS_USER' AND COLUMN_NAME='ROLES') THEN
  ALTER TABLE OPERATIONS_USER DROP COLUMN ROLES;
END IF;
END#

DROP PROCEDURE IF EXISTS fix_operations#