ALTER TABLE ACCOUNT_SESSION ADD COLUMN PLATFORM VARCHAR(32) NULL AFTER REFERER, ADD INDEX IDX_PLATFORM (PLATFORM ASC)#
ALTER TABLE EXTERNAL_TRANSACTION ADD COLUMN PLATFORM VARCHAR(32) NULL AFTER GAME_TYPE, ADD INDEX IDX_PLATFORM (PLATFORM ASC)#
