ALTER TABLE PROMOTION_ARCHIVE ADD COLUMN CONTROL_GROUP_PERCENTAGE INT NOT NULL DEFAULT 0  AFTER PRIORITY,
ADD COLUMN SEED INT NOT NULL DEFAULT 0  AFTER PRIORITY#

alter table PROMOTION_PLAYER_REWARD_ARCHIVE add column CONTROL_GROUP tinyint(1) not null default 0 after player_id#