
CREATE TABLE IF NOT EXISTS `IOS_PUSH_NOTIFICATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(256) NOT NULL DEFAULT '',
  `DESCRIPTION` varchar(256) NOT NULL DEFAULT '',
  `MESSAGE` varchar(100) NOT NULL DEFAULT '',
  `CREATED` datetime NOT NULL,
  `SENT` datetime NULL,
  `MESSAGES_SENT_COUNT` int(11) NOT NULL DEFAULT '0',
  `STATUS` tinyint(1) NOT NULL DEFAULT '0',
    
  PRIMARY KEY (`ID`),
  KEY `IDX_CREATED` (`CREATED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8#


CREATE TABLE IF NOT EXISTS `IOS_PUSH_NOTIFICATION_TARGET` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOTIFICATION_ID` int(11) NOT NULL,
  `GAME_TYPE` varchar(255) NOT NULL,
  `PLAYER_ID` bigint(20) NOT NULL,

  PRIMARY KEY (`ID`),
  KEY `IDX_NOTIFICATION_PLAYER` (`NOTIFICATION_ID`, `GAME_TYPE`, `PLAYER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8#

