maintainer       "Example Com"
maintainer_email "ops@example.com"
license          "Apache 2.0"
description      "Installs the JDK"
long_description "Installs the JDK"
version          "0.1"
name			 "java"
