-- Table: audit_command
CREATE TABLE AUDIT_COMMAND (
  auto_id bigint IDENTITY(1,1) NOT NULL,
  AUDIT_LABEL character varying(255) NOT NULL,
  HOSTNAME character varying(255) NOT NULL,
  AUDIT_TS timestamp SORTKEY,
  DBWRITE_TS timestamp ,
  COMMAND_ID character varying(255) NOT NULL,
  TABLE_ID DECIMAL(16,2) NOT NULL,
  GAME_ID DECIMAL(16,2),
  PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY,
  COMMAND_TYPE character varying(255) NOT NULL,
  COMMAND_ARGS character varying(max),
  PRIMARY KEY (auto_id),
  FOREIGN KEY(PLAYER_ID) REFERENCES LOBBY_USER(PLAYER_ID)
)
;
GRANT SELECT ON AUDIT_COMMAND TO GROUP READ_ONLY;
GRANT ALL ON AUDIT_COMMAND TO GROUP READ_WRITE;
GRANT ALL ON AUDIT_COMMAND TO GROUP SCHEMA_MANAGER;
