-- WEB-4273 - add guest status column to LOBBY_USER

ALTER TABLE LOBBY_USER ADD COLUMN GUEST_STATUS VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE STG_LOBBY_USER ADD COLUMN GUEST_STATUS VARCHAR(1) NOT NULL DEFAULT 'N';
