-- Table: TABLE_DEFINITION
CREATE TABLE TABLE_DEFINITION (
  TABLE_ID DECIMAL(16,2) NOT NULL DISTKEY SORTKEY PRIMARY KEY,
  GAME_VARIATION_TEMPLATE_ID DECIMAL(16,2) NOT NULL
)
;
GRANT SELECT ON TABLE_DEFINITION TO GROUP READ_ONLY;
GRANT ALL ON TABLE_DEFINITION TO GROUP READ_WRITE;
GRANT ALL ON TABLE_DEFINITION TO GROUP SCHEMA_MANAGER;

