-- WEB-4326 - increase exchange rate precision to match WorldPay

-- Done in a round-about manner as Redshift doesn't support type changes. Go Redshift!

ALTER TABLE EXTERNAL_TRANSACTION RENAME COLUMN EXCHANGE_RATE TO EXCHANGE_RATE_OLD;
ALTER TABLE EXTERNAL_TRANSACTION ADD COLUMN EXCHANGE_RATE NUMERIC(13,7);

UPDATE EXTERNAL_TRANSACTION SET EXCHANGE_RATE=EXCHANGE_RATE_OLD WHERE EXCHANGE_RATE_OLD IS NOT NULL;

ALTER TABLE EXTERNAL_TRANSACTION DROP COLUMN EXCHANGE_RATE_OLD;
