CREATE TABLE GIFTS_SENT(
  gift_id BIGINT NOT NULL DISTKEY,
  sender_id DECIMAL(16,2) NOT NULL,
  receiver_id DECIMAL(16,2) NOT NULL,
  expiry_ts timestamp,
  sent_ts timestamp SORTKEY,
  PRIMARY KEY (gift_id));

GRANT SELECT ON GIFTS_SENT TO GROUP READ_ONLY;
GRANT ALL ON GIFTS_SENT TO GROUP READ_WRITE;
GRANT ALL ON GIFTS_SENT TO GROUP SCHEMA_MANAGER;