CREATE TABLE GIFTS_COLLECTED(
  gift_id BIGINT NOT NULL DISTKEY SORTKEY,
  choice varchar(128) NOT NULL,
  amount DECIMAL(16,2) NOT NULL,
  PRIMARY KEY (gift_id));

GRANT SELECT ON GIFTS_COLLECTED TO GROUP READ_ONLY;
GRANT ALL ON GIFTS_COLLECTED TO GROUP READ_WRITE;
GRANT ALL ON GIFTS_COLLECTED TO GROUP SCHEMA_MANAGER;