drop table adnet_mappings;

CREATE TABLE adnet_mappings(
  referrer character varying(255) NOT NULL,
  registration_adnet character varying(32),
  PRIMARY KEY(referrer));

GRANT SELECT ON adnet_mappings TO GROUP READ_ONLY;
GRANT ALL ON adnet_mappings TO GROUP READ_WRITE;
GRANT ALL ON adnet_mappings TO GROUP SCHEMA_MANAGER;

insert into adnet_mappings (referrer,registration_adnet) values
('16838121','Organic')
,('302','Organic')
,('ADP%','AdParlor')
,('AD_REFERENCE%','Web - Facebook')
,('AE_%','Web - Facebook')
,('AR_%','Web - Facebook')
,('AU_%','Web - Facebook')
,('AdTest%','Web - Facebook')
,('BINGO-%','Web - Facebook')
,('BLACKJACK_%','Viral')
,('BR_%','Web - Facebook')
,('Blog%','Organic')
,('CA_%','Web - Facebook')
,('DE_%','Web - Facebook')
,('Email%','Organic')
,('FB-Yazino-wall_PreBastilleDay-13July','Organic')
,('FBAPP%','Organic')
,('FBContest%','Organic')
,('FBCoverPhoto%','Organic')
,('FBFanPage%','Organic')
,('FBN_%','Organic')
,('FBPage_%','Organic')
,('FBWALL%','Organic')
,('FBWDFanPage%','Organic')
,('FB_%','Organic')
,('FBapp%','Organic')
,('FBwall%','Organic')
,('FR_%','Web - Facebook')
,('FbWall%','Organic')
,('GB_%','Web - Facebook')
,('HK_%','Web - Facebook')
,('HSFan-tasticSweepstakes','Organic')
,('ID_%','Web - Facebook')
,('INVITE%','Viral')
,('InviteFriends%','Organic')
,('IN_%','Web - Facebook')
,('LB_%','Web - Facebook')
,('MY_%','Web - Facebook')
,('NL_%','Web - Facebook')
,('NZ_%','Web - Facebook')
,('Opt_%','Web - Facebook')
,('PH_%','Web - Facebook')
,('PL_%','Web - Facebook')
,('POKER-%','Web - Facebook')
,('ReelBuddies_15092013','Organic')
,('SG_%','Web - Facebook')
,('SLOTS_TRIPILETTO_WHEEL_WIN_LO','Viral')
,('SWD%','Web - InGaming')
,('SupportSignature%','Organic')
,('TR_%','Web - Facebook')
,('Twitter%','Organic')
,('US_%','Web - Facebook')
,('WD-FanVotesApp_21082012','Organic')
,('WDFanPage_PersonalityTestApp','Organic')
,('WEB_STEPH_TEST2%','Organic')
,('WEB_TEST_STEPH%','Organic')
,('XXXXXXX%','Organic')
,('ZA_%','Web - Facebook')
,('___%','Viral')
,('acount=0%','Organic')
,('ad%','Organic')
,('aggregation%','Organic')
,('ales_test%','Organic')
,('and_chartboost%','Android - Chartboost')
,('and_inmobi%','Android - Inmobi')
,('and_internal_test_11jul%','Organic')
,('and_manage%','Android - Manage')
,('and_tapjoy_incent%','Android - Tapjoy incent')
,('and_wd_adbud%','Android - Adbud')
,('and_wd_adgorithm%','Android - Adgorithm')
,('and_wd_androidpit%','Android - Androidpit')
,('and_wd_appgratis%','Android - Appgratis')
,('and_wd_appia%','Android - Appia')
,('and_wd_applift%','Android - Applift')
,('and_wd_appsfire%','Android - Appsfire')
,('and_wd_chartboost%','Android - Chartboost')
,('and_wd_facebook%','Android - Facebook')
,('and_wd_fiksu_aarki%','Android - Fiksu Aarki')
,('and_wd_fiksu_adcolony%','Android - Fiksu Adcolony')
,('and_wd_fiksu_adwords%','Android - Fiksu Adwords')
,('and_wd_fiksu_aerify%','Android - Fiksu Aerify')
,('and_wd_fiksu_airpush%','Android - Fiksu Airpush')
,('and_wd_fiksu_appia%','Android - Fiksu Appia')
,('and_wd_fiksu_applovin%','Android - Fiksu Applovin')
,('and_wd_fiksu_best apps market%','Android - Fiksu Best')
,('and_wd_fiksu_chartboost%','Android - Fiksu Chartboost')
,('and_wd_fiksu_flurry%','Android - Fiksu Flurry')
,('and_wd_fiksu_freemyapps%','Android - Fiksu FreeMyApps')
,('and_wd_fiksu_freemyapps- sponsor apps%','Android - Fiksu Freemyapps')
,('and_wd_fiksu_grindr%','Android - Fiksu Grindr')
,('and_wd_fiksu_sponsorpay%','Android - Fiksu Sponsorpay')
,('and_wd_fiksu_tapjoy%','Android - Fiksu Tapjoy')
,('and_wd_fiksu_w3i%','Android - Fiksu w3i')
,('and_wd_getjar%','Android - Getjar')
,('and_wd_glow%','Android - Glow')
,('and_wd_jumptap%','Android - Jumptap')
,('and_wd_manage%','Android - Manage')
,('and_wd_perforrev%','Android - Perforrev')
,('and_wd_saatchi%','Android - Saatchi')
,('and_wd_seccosquared%','Android - Seccosquared')
,('and_wd_tapjoyvideo%','Android - Tapjoy video')
,('and_wd_vungle%','Android - Vungle')
,('and_wdtapjoyvideo%','Android - Tapjoy video')
,('app%','Organic')
,('ar_%','Web - Facebook')
,('at_%','Web - Facebook')
,('au_%','Web - Facebook')
,('bg_%','Web - Facebook')
,('bingoBJ_%','Web - Facebook')
,('boo','Organic')
,('booja','Organic')
,('bookmark%','Organic')
,('br_slot%','Web - Facebook')
,('br_tf%','Organic')
,('ca_%','Web - Facebook')
,('canvas%','Organic')
,('colombus_day%','Web - Facebook')
,('cust%','Web - FB Reactivation')
,('cz_%','Web - Facebook')
,('de_%','Web - Facebook')
,('dialog%','Organic')
,('dk_%','Web - Facebook')
,('ec_','Web - Facebook')
,('ego%','Organic')
,('email%','Organic')
,('es_%','Web - Facebook')
,('facebook%','Organic')
,('fb%','Organic')
,('feed%','Organic')
,('fr_%','Web - Facebook')
,('games%','Organic')
,('gb_%','Web - Facebook')
,('gr_%','Web - Facebook')
,('hovercard%','Organic')
,('hu_%','Web - Facebook')
,('id_%','Web - Facebook')
,('ios_applift%','iOS - Applift')
,('ios_bj_public_page%','Organic')
,('ios_chartboost%','iOS - Chartboost')
,('ios_hs_public_page%','Organic')
,('ios_inmobi%','iOS - Inmobi')
,('ios_manage%','iOS - Manage')
,('ios_tapjoy','iOS - Tapjoy')
,('ios_tapjoy_incentivised%','iOS - Tapjoy incent')
,('ios_tapjoy_ipad%','iOS - Tapjoy')
,('ios_tapjoy_iphone%','iOS - Tapjoy')
,('ios_wd_appgratis%','iOS - Appgratis')
,('ios_wd_appturbo%','iOS - Appturbo')
,('ios_wd_appsfire%','iOS - Appsfire')
,('ios_wd_fb_%','iOS - Facebook')
,('ios_wd_manage%','iOS - Manage')
,('ios_wd_mediaswapp%','iOS - Mediaswapp')
,('ios_wd_misterbell%','iOS - Misterbell')
,('ios_wd_public_page%','Organic')
,('ios_wd_tapjoy_video%','iOS - Tapjoy')
,('ios_wd_vungle%','iOS - Vungle')
,('it_slot%','Web - Facebook')
,('ivan_test%','Organic')
,('keyword_search%','Organic')
,('latam_slot_%','Web - Facebook')
,('md_%','Web - Maudau')
,('mx_%','Web - Facebook')
,('my_%','Web - Facebook')
,('myapps%','Organic')
,('nf%','Viral')
,('no_%','Web - Facebook')
,('nordic_%','Web - Facebook')
,('notif%','Organic')
,('nz_%','Web - Facebook')
,('other_multiline%','Organic')
,('passive_action%','Organic')
,('ph_slot%','Web - Facebook')
,('pl_%','Web - Facebook')
,('profile%','Organic')
,('progressive_bonus%','Organic')
,('pt_slot%','Web - Facebook')
,('reminder_pok_m20_1','Web - Facebook')
,('reminders%','Organic')
,('request%','Organic')
,('retention_wd_us_f30_jul13_1','Web - Facebook')
,('rs_%','Web - Facebook')
,('search%','Organic')
,('slot_%','Web - Facebook')
,('slots_%','Web - Facebook')
,('sw_slot_%','Web - Facebook')
,('swd99999test%','Organic')
,('test_icanhascheezburger%','Organic')
,('th_%','Web - Facebook')
,('this_is_a_mofo_test%','Organic')
,('ticker%','Organic')
,('timeline%','Organic')
,('tn_tnmn%','Organic')
,('tr_slot%','Web - Facebook')
,('try3%','Organic')
,('ts','Organic')
,('tsÃƒ?Ã‚Âx1CÃƒ?Ã‚Â%','Organic')
,('twitter%','Organic')
,('uk_%','Web - Facebook')
,('unknown%','Organic')
,('us_%','Web - Facebook')
,('ve_%','Web - Facebook')
,('vucp_slot%','Web - Facebook')
,('web_motive%','Web - Motive')
,('web_search%','Organic')
;

