-- Table: GAME_VARIATION_TEMPLATE
CREATE TABLE GAME_VARIATION_TEMPLATE (
  GAME_VARIATION_TEMPLATE_ID DECIMAL(16,2) NOT NULL DISTKEY PRIMARY KEY,
  GAME_TYPE character varying(255) SORTKEY,
  NAME character varying(255)
)
;
GRANT SELECT ON GAME_VARIATION_TEMPLATE TO GROUP READ_ONLY;
GRANT ALL ON GAME_VARIATION_TEMPLATE TO GROUP READ_WRITE;
GRANT ALL ON GAME_VARIATION_TEMPLATE TO GROUP SCHEMA_MANAGER;

