CREATE TABLE CLIENT_CONTEXT(
  session_id BIGINT NOT NULL DISTKEY SORTKEY,
  device_id varchar(128),
  PRIMARY KEY (session_id));

GRANT SELECT ON CLIENT_CONTEXT TO GROUP READ_ONLY;
GRANT ALL ON CLIENT_CONTEXT TO GROUP READ_WRITE;
GRANT ALL ON CLIENT_CONTEXT TO GROUP SCHEMA_MANAGER;