-- Table: transaction_log
CREATE TABLE TRANSACTION_LOG (
  TRANSACTION_LOG_ID BIGINT IDENTITY(1,1) NOT NULL,
  ACCOUNT_ID DECIMAL(16,2) NOT NULL DISTKEY,
  AMOUNT numeric(32, 4) NOT NULL,
  REFERENCE character varying(255),
  EXECUTED_TS timestamp without time zone DEFAULT SYSDATE NOT NULL,
  VERSION integer DEFAULT 0 NOT NULL,
  TRANSACTION_TYPE character varying(32) NOT NULL,
  AUDIT_LABEL character varying(255),
  TRANSACTION_TS timestamp without time zone DEFAULT SYSDATE NOT NULL SORTKEY,
  RUNNING_BALANCE numeric(32, 4),
  TRANSACTION_TS_MILLIS integer DEFAULT 0 NOT NULL,
  GAME_ID DECIMAL(16,2),
  TABLE_ID DECIMAL(16,2),
  PRIMARY KEY (TRANSACTION_LOG_ID)
)
;
GRANT SELECT ON TRANSACTION_LOG TO GROUP READ_ONLY;
GRANT ALL ON TRANSACTION_LOG TO GROUP READ_WRITE;
GRANT ALL ON TRANSACTION_LOG TO GROUP SCHEMA_MANAGER;
