DROP TABLE IF EXISTS MESSAGING_PLAYER_DEVICE_REGISTRATION;

CREATE TABLE MESSAGING_PLAYER_DEVICE_REGISTRATION (
  PLAYER_ID decimal(16,2) NOT NULL,
  GAME_TYPE varchar(255) NOT NULL,
  PLATFORM varchar(255) NOT NULL,
  REGISTRATION_ID text NOT NULL,
  LAST_UPDATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

alter table MESSAGING_PLAYER_DEVICE_REGISTRATION add PRIMARY KEY (PLAYER_ID, GAME_TYPE, PLATFORM);

GRANT SELECT ON MESSAGING_PLAYER_DEVICE_REGISTRATION TO GROUP READ_ONLY;
GRANT ALL ON MESSAGING_PLAYER_DEVICE_REGISTRATION TO GROUP READ_WRITE;
GRANT ALL ON MESSAGING_PLAYER_DEVICE_REGISTRATION TO GROUP SCHEMA_MANAGER;
---
DROP TABLE IF EXISTS PLAYER_PROMOTION_STATUS;

CREATE TABLE PLAYER_PROMOTION_STATUS (
  PLAYER_ID decimal(16,2) NOT NULL,
  LAST_TOPUP_DATE timestamp DEFAULT NULL,
  LAST_PLAYED_DATE timestamp DEFAULT NULL,
  CONSECUTIVE_PLAY_DAYS integer DEFAULT '0',
  TOP_UP_ACKNOWLEDGED boolean DEFAULT NULL,
  PRIMARY KEY (PLAYER_ID)
);
GRANT SELECT ON PLAYER_PROMOTION_STATUS TO GROUP READ_ONLY;
GRANT ALL ON PLAYER_PROMOTION_STATUS TO GROUP READ_WRITE;
GRANT ALL ON PLAYER_PROMOTION_STATUS TO GROUP SCHEMA_MANAGER;
--
DROP TABLE IF EXISTS CAMPAIGN_RUN;

CREATE TABLE IF NOT EXISTS CAMPAIGN_RUN (
  ID serial NOT NULL,
  CAMPAIGN_ID integer,
  RUN_TS timestamp default now(),
  PRIMARY KEY (ID)
);
GRANT USAGE, SELECT ON SEQUENCE campaign_run_id_seq TO READ_ONLY;
GRANT USAGE, SELECT ON SEQUENCE campaign_run_id_seq TO READ_WRITE;
GRANT USAGE, SELECT ON SEQUENCE campaign_run_id_seq TO SCHEMA_MANAGER;
GRANT SELECT ON CAMPAIGN_RUN TO GROUP READ_ONLY;
GRANT ALL ON CAMPAIGN_RUN TO GROUP READ_WRITE;
GRANT ALL ON CAMPAIGN_RUN TO GROUP SCHEMA_MANAGER;
