-- Table: TOURNAMENT_PLAYER
CREATE TABLE TOURNAMENT_PLAYER (
  TOURNAMENT_ID DECIMAL(16,2) NOT NULL ,
  PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY SORTKEY,
  PRIMARY KEY(tournament_id, player_id),
  FOREIGN KEY(PLAYER_ID) REFERENCES LOBBY_USER(PLAYER_ID)
)
;
GRANT SELECT ON TOURNAMENT_PLAYER TO GROUP READ_ONLY;
GRANT ALL ON TOURNAMENT_PLAYER TO GROUP READ_WRITE;
GRANT ALL ON TOURNAMENT_PLAYER TO GROUP SCHEMA_MANAGER;

