-- Table: TOURNAMENT_PLAYER_SUMMARY
CREATE TABLE TOURNAMENT_PLAYER_SUMMARY (
  PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY SORTKEY,
  TOURNAMENT_ID DECIMAL(16,2) NOT NULL,
  POSITION integer NOT NULL,
  PRIZE bigint NOT NULL,
  PRIMARY KEY (PLAYER_ID,TOURNAMENT_ID),
  FOREIGN KEY(PLAYER_ID) REFERENCES LOBBY_USER(PLAYER_ID)
)
;
GRANT SELECT ON TOURNAMENT_PLAYER_SUMMARY TO GROUP READ_ONLY;
GRANT ALL ON TOURNAMENT_PLAYER_SUMMARY TO GROUP READ_WRITE;
GRANT ALL ON TOURNAMENT_PLAYER_SUMMARY TO GROUP SCHEMA_MANAGER;

