-- Table: TOURNAMENT_SUMMARY
CREATE TABLE TOURNAMENT_SUMMARY (
  TOURNAMENT_ID DECIMAL(16,2) NOT NULL DISTKEY PRIMARY KEY,
  TOURNAMENT_NAME character varying(255),
  TOURNAMENT_FINISHED_TS timestamp without time zone SORTKEY
)
;
GRANT SELECT ON TOURNAMENT_SUMMARY TO GROUP READ_ONLY;
GRANT ALL ON TOURNAMENT_SUMMARY TO GROUP READ_WRITE;
GRANT ALL ON TOURNAMENT_SUMMARY TO GROUP SCHEMA_MANAGER;

