-- Table: EXTERNAL_TRANSACTION
CREATE TABLE EXTERNAL_TRANSACTION (
  AUTO_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  ACCOUNT_ID DECIMAL(16,2) DISTKEY NOT NULL,
  INTERNAL_TRANSACTION_ID character varying(255) NOT NULL,
  EXTERNAL_TRANSACTION_ID character varying(255),
  MESSAGE character varying(max) NOT NULL,
  MESSAGE_TS timestamp without time zone DEFAULT SYSDATE NOT NULL SORTKEY,
  CURRENCY_CODE character varying(3) NOT NULL,
  AMOUNT numeric(32, 4) NOT NULL,
  CREDIT_CARD_NUMBER character varying(16) NOT NULL,
  CASHIER_NAME character varying(255) NOT NULL,
  EXTERNAL_TRANSACTION_STATUS character varying(255),
  AMOUNT_CHIPS numeric(32, 4) DEFAULT 0.0000 NOT NULL,
  VERSION integer DEFAULT 0 NOT NULL,
  TRANSACTION_TYPE character varying(32),
  GAME_TYPE character varying(255),
  PLATFORM character varying(32),
  FAILURE_REASON character varying(255)
)
;
GRANT SELECT ON EXTERNAL_TRANSACTION TO GROUP READ_ONLY;
GRANT ALL ON EXTERNAL_TRANSACTION TO GROUP READ_WRITE;
GRANT ALL ON EXTERNAL_TRANSACTION TO GROUP SCHEMA_MANAGER;

