-- Table: CURRENCY_RATES
CREATE TABLE CURRENCY_RATES (
  CURRENCY_CODE varchar NOT NULL DISTKEY SORTKEY PRIMARY KEY,
  RATE numeric(32,4)
)
;
GRANT SELECT ON CURRENCY_RATES TO GROUP READ_ONLY;
GRANT ALL ON CURRENCY_RATES TO GROUP READ_WRITE;
GRANT ALL ON CURRENCY_RATES TO GROUP SCHEMA_MANAGER;
