CREATE VIEW TABLE_INFO
AS SELECT
T.TABLE_ID AS TABLE_ID,(V.NAME || T.TABLE_ID) AS TABLE_NAME, V.GAME_TYPE AS GAME_TYPE,T.GAME_VARIATION_TEMPLATE_ID AS GAME_VARIATION_TEMPLATE_ID
FROM TABLE_DEFINITION T join GAME_VARIATION_TEMPLATE V
on (T.GAME_VARIATION_TEMPLATE_ID = V.GAME_VARIATION_TEMPLATE_ID);

GRANT SELECT ON TABLE_INFO TO GROUP READ_ONLY;
GRANT ALL ON TABLE_INFO TO GROUP READ_WRITE;
GRANT ALL ON TABLE_INFO TO GROUP SCHEMA_MANAGER;
