-- Table: INVITATIONS
CREATE TABLE INVITATIONS (
  PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY,
  RECIPIENT_IDENTIFIER character varying(255) NOT NULL,
  INVITED_FROM character varying(10) NOT NULL,
  STATUS character varying(20) NOT NULL,
  REWARD integer,
  CREATED_TS timestamp without time zone DEFAULT SYSDATE NOT NULL SORTKEY,
  UPDATED_TS timestamp without time zone DEFAULT SYSDATE NOT NULL NOT NULL,
  GAME_TYPE character varying(32),
  SCREEN_SOURCE character varying(32),
  PRIMARY KEY (PLAYER_ID,RECIPIENT_IDENTIFIER,INVITED_FROM),
  FOREIGN KEY(PLAYER_ID) REFERENCES LOBBY_USER(PLAYER_ID)
)
;
GRANT SELECT ON INVITATIONS TO GROUP READ_ONLY;
GRANT ALL ON INVITATIONS TO GROUP READ_WRITE;
GRANT ALL ON INVITATIONS TO GROUP SCHEMA_MANAGER;
