CREATE TABLE player_activity_daily (
PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY PRIMARY KEY,
GAME varchar(255),
PLATFORM varchar(255),
ACTIVITY_TS timestamp not null DEFAULT SYSDATE SORTKEY,
REFERRER varchar(255),
REG_DATE date
);

GRANT SELECT ON player_activity_daily TO GROUP READ_ONLY;
GRANT ALL ON player_activity_daily TO GROUP READ_WRITE;
GRANT ALL ON player_activity_daily TO GROUP SCHEMA_MANAGER;