-- Table: PLAYER_LEVEL
CREATE TABLE STG_PLAYER_LEVEL (
  PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY SORTKEY,
  GAME_TYPE character varying(255) NOT NULL,
  LEVEL integer NOT NULL,
  PRIMARY KEY (PLAYER_ID, GAME_TYPE)
)
;
GRANT SELECT ON STG_PLAYER_LEVEL TO GROUP READ_ONLY;
GRANT ALL ON STG_PLAYER_LEVEL TO GROUP READ_WRITE;
GRANT ALL ON STG_PLAYER_LEVEL TO GROUP SCHEMA_MANAGER;