-- Table: TOURNAMENT_VARIATION_TEMPLATE
CREATE TABLE STG_TOURNAMENT_VARIATION_TEMPLATE (
  TOURNAMENT_VARIATION_TEMPLATE_ID DECIMAL(16,2) NOT NULL DISTKEY PRIMARY KEY,
  GAME_TYPE character varying(255) NOT NULL SORTKEY
)
;
GRANT SELECT ON STG_TOURNAMENT_VARIATION_TEMPLATE TO GROUP READ_ONLY;
GRANT ALL ON STG_TOURNAMENT_VARIATION_TEMPLATE TO GROUP READ_WRITE;
GRANT ALL ON STG_TOURNAMENT_VARIATION_TEMPLATE TO GROUP SCHEMA_MANAGER;
