
-- Table: PLAYER_LEVEL
CREATE TABLE PLAYER_LEVEL (
  PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY SORTKEY PRIMARY KEY,
  GAME_TYPE character varying(255) NOT NULL,
  LEVEL integer NOT NULL,
  FOREIGN KEY(PLAYER_ID) REFERENCES LOBBY_USER(PLAYER_ID)
)
;
GRANT SELECT ON PLAYER_LEVEL TO GROUP READ_ONLY;
GRANT ALL ON PLAYER_LEVEL TO GROUP READ_WRITE;
GRANT ALL ON PLAYER_LEVEL TO GROUP SCHEMA_MANAGER;
