CREATE TABLE STG_PLAYER_REFERRER (
  PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY SORTKEY PRIMARY KEY,
  REGISTRATION_REFERRER character varying(255),
  REGISTRATION_PLATFORM character varying(32),
  REGISTRATION_GAME_TYPE character varying(32)
)
;
GRANT SELECT ON STG_PLAYER_REFERRER TO GROUP READ_ONLY;
GRANT ALL ON STG_PLAYER_REFERRER TO GROUP READ_WRITE;
GRANT ALL ON STG_PLAYER_REFERRER TO GROUP SCHEMA_MANAGER;
