-- Table: player_definition
CREATE TABLE STG_PLAYER_DEFINITION (
  PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY PRIMARY KEY,
  CREATED_TS timestamp without time zone SORTKEY,
  ACCOUNT_ID DECIMAL(16,2)
)
;
GRANT SELECT ON PLAYER_DEFINITION TO GROUP READ_ONLY;
GRANT ALL ON PLAYER_DEFINITION TO GROUP READ_WRITE;
GRANT ALL ON PLAYER_DEFINITION TO GROUP SCHEMA_MANAGER;