-- Table: account_session
CREATE TABLE ACCOUNT_SESSION (
  SESSION_ID bigint IDENTITY(1,1) NOT NULL,
  ACCOUNT_ID DECIMAL(16,2) NOT NULL DISTKEY,
  SESSION_KEY character varying(255) NOT NULL,
  START_TS timestamp without time zone DEFAULT SYSDATE NOT NULL SORTKEY,
  VERSION integer DEFAULT 0 NOT NULL,
  IP_ADDRESS character varying(40),
  REFERER character varying(2048),
  PLATFORM character varying(32),
  START_PAGE character varying(2048),
  PRIMARY KEY (SESSION_ID,START_TS)
)
;
GRANT SELECT ON ACCOUNT_SESSION TO GROUP READ_ONLY;
GRANT ALL ON ACCOUNT_SESSION TO GROUP READ_WRITE;
GRANT ALL ON ACCOUNT_SESSION TO GROUP SCHEMA_MANAGER;

