GRANT SELECT ON STG_LOBBY_USER TO GROUP READ_ONLY;
GRANT ALL ON STG_LOBBY_USER TO GROUP READ_WRITE;
GRANT ALL ON STG_LOBBY_USER TO GROUP SCHEMA_MANAGER;

GRANT SELECT ON STG_PLAYER_DEFINITION TO GROUP READ_ONLY;
GRANT ALL ON STG_PLAYER_DEFINITION TO GROUP READ_WRITE;
GRANT ALL ON STG_PLAYER_DEFINITION TO GROUP SCHEMA_MANAGER;
