-- Table: audit_closed_game
CREATE TABLE AUDIT_CLOSED_GAME (
  auto_id bigint IDENTITY(1,1) NOT NULL,
  AUDIT_LABEL character varying(255) NOT NULL,
  HOSTNAME character varying(255) NOT NULL,
  AUDIT_TS timestamp without time zone NOT NULL SORTKEY,
  DBWRITE_TS timestamp without time zone DEFAULT SYSDATE NOT NULL,
  TABLE_ID DECIMAL(16,2) DISTKEY,
  GAME_ID DECIMAL(16,2),
  GAME_INCREMENT integer,
  OBSERVABLE_STATUS character varying(max),
  INTERNAL_STATUS character varying(max),
  PRIMARY KEY (auto_id,AUDIT_TS)
)
;
GRANT SELECT ON AUDIT_CLOSED_GAME TO GROUP READ_ONLY;
GRANT ALL ON AUDIT_CLOSED_GAME TO GROUP READ_WRITE;
GRANT ALL ON AUDIT_CLOSED_GAME TO GROUP SCHEMA_MANAGER;
