
DROP TABLE STG_FACEBOOK_AD_STATS;

CREATE TABLE STG_FACEBOOK_AD_STATS(
   TRACKING_DATE date DISTKEY NOT NULL,
   SOURCE varchar(255) NOT NULL,
   CLICKS int DEFAULT 0 NOT NULL,
   IMPRESSIONS int DEFAULT 0 NOT NULL,
   SPENT bigint DEFAULT 0 NOT NULL,
   PRIMARY KEY (TRACKING_DATE,SOURCE)
)SORTKEY(TRACKING_DATE,SOURCE);

GRANT SELECT ON STG_FACEBOOK_AD_STATS TO GROUP READ_ONLY;
GRANT ALL ON STG_FACEBOOK_AD_STATS TO GROUP READ_WRITE;
GRANT ALL ON STG_FACEBOOK_AD_STATS TO GROUP SCHEMA_MANAGER;

INSERT INTO MAINTENANCE (TABLE_NAME, KEY_COLUMNS, VACUUMED, TABLE_ANALYSED, KEYS_ANALYSED) VALUES
  ('stg_facebook_ad_stats', 'TRACKING_DATE,SOURCE','2011-01-01 11:11:11','2011-01-01 11:11:11','2011-01-01 11:11:11');
