CREATE TABLE CAMPAIGN_RUN_AUDIT(
   CAMPAIGN_ID bigint NOT NULL DISTKEY,
   RUN_ID bigint NOT NULL,
   NAME character varying(max),
   SEGMENT_SIZE bigint DEFAULT 0 NOT NULL,
   RUN_TS TIMESTAMP SORTKEY,
   PRIMARY KEY (CAMPAIGN_ID,RUN_ID)
);

GRANT SELECT ON CAMPAIGN_RUN_AUDIT TO GROUP READ_ONLY;
GRANT ALL ON CAMPAIGN_RUN_AUDIT TO GROUP READ_WRITE;
GRANT ALL ON CAMPAIGN_RUN_AUDIT TO GROUP SCHEMA_MANAGER;
