-- Table: audit_closed_game_player
CREATE TABLE AUDIT_CLOSED_GAME_PLAYER (
  auto_id bigint IDENTITY(1,1) NOT NULL,
  AUDIT_LABEL character varying(255) NOT NULL,
  HOSTNAME character varying(255) NOT NULL,
  AUDIT_TS timestamp without time zone NOT NULL SORTKEY,
  DBWRITE_TS timestamp without time zone DEFAULT SYSDATE NOT NULL,
  TABLE_ID DECIMAL(16,2) NOT NULL DISTKEY,
  GAME_ID DECIMAL(16,2) NOT NULL,
  PLAYER_ID bigint NOT NULL,
  PRIMARY KEY (auto_id,AUDIT_TS),
  FOREIGN KEY(PLAYER_ID) REFERENCES LOBBY_USER(PLAYER_ID)
)
;
GRANT SELECT ON AUDIT_CLOSED_GAME_PLAYER TO GROUP READ_ONLY;
GRANT ALL ON AUDIT_CLOSED_GAME_PLAYER TO GROUP READ_WRITE;
GRANT ALL ON AUDIT_CLOSED_GAME_PLAYER TO GROUP SCHEMA_MANAGER;

