DROP TABLE CAMPAIGN_NOTIFICATION_AUDIT;

CREATE TABLE CAMPAIGN_NOTIFICATION_AUDIT(
   CAMPAIGN_RUN_ID bigint NOT NULL,
   PLAYER_ID DECIMAL(16,2) NOT NULL DISTKEY,
   CHANNEL varchar(50) NOT NULL,
   GAME_TYPE varchar(50) NOT NULL,
   NOTIFICATION_AUDIT_TYPE varchar(50) NOT NULL,
   RUN_TS TIMESTAMP,
   PRIMARY KEY (CAMPAIGN_RUN_ID,PLAYER_ID,CHANNEL,GAME_TYPE,NOTIFICATION_AUDIT_TYPE)
)SORTKEY(CAMPAIGN_RUN_ID,PLAYER_ID,CHANNEL,GAME_TYPE,NOTIFICATION_AUDIT_TYPE);

GRANT SELECT ON CAMPAIGN_NOTIFICATION_AUDIT TO GROUP READ_ONLY;
GRANT ALL ON CAMPAIGN_NOTIFICATION_AUDIT TO GROUP READ_WRITE;
GRANT ALL ON CAMPAIGN_NOTIFICATION_AUDIT TO GROUP SCHEMA_MANAGER;

DELETE FROM MAINTENANCE WHERE TABLE_NAME='campaign_notification_audit';

INSERT INTO MAINTENANCE (TABLE_NAME, KEY_COLUMNS, VACUUMED, TABLE_ANALYSED, KEYS_ANALYSED) VALUES
  ('campaign_notification_audit', 'CAMPAIGN_RUN_ID,PLAYER_ID,CHANNEL,GAME_TYPE,NOTIFICATION_AUDIT_TYPE','2011-01-01 11:11:11','2011-01-01 11:11:11','2011-01-01 11:11:11');