package com.yazino.platform.messaging;

public enum DocumentType {
    ERROR("ERROR"),
    GAME_STATUS("GAME_STATUS"),
    INITIAL_GAME_STATUS("INITIAL_GAME_STATUS"),
    MESSAGE("MESSAGE"),
    COMMUNITY_STATUS("PLAYER_STATUS"),
    OWN_LOCATION_CHANGE("OWN_LOCATION_CHANGE"),
    COMMUNITY_PLAYER_RELATIONSHIP("PLAYER_RELATIONSHIP"),
    FRIENDS_SUMMARY("FRIENDS_SUMMARY"),
    CHAT_CHANNEL_STATUS("CHAT_CHANNEL_STATUS"),
    CHAT_MESSAGE("CHAT_MESSAGE"),
    NEWS_EVENT("NEWS_EVENT"),
    AWARD_MEDAL_EVENT("AWARD_MEDAL_EVENT"),
    PLAYER_BALANCE("PLAYER_BALANCE"),
    PLAYER_XP("PLAYER_XP"),
    TABLE_INVITES("TABLE_INVITES"),
    COUNTDOWN("COUNTDOWN"),
    SHUTDOWN("SHUTDOWN"),
    GIFT_RECEIVED("GIFT_RECEIVED"),
    GIFTING_PLAYER_COLLECTION_STATUS("GIFTING_PLAYER_COLLECTION_STATUS"),
    TROPHY_LEADERBOARD_PLAYER_UPDATE("TROPHY_LEADERBOARD_PLAYER_UPDATE"),;

    private String name;

    private DocumentType(final String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
